### PR TITLE
Make friend message callback stateless

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/48)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48#-:-KPYzN5JRWwJqYjSxfjP:bnfp4nl)*

**Comment by iphydf** [comment]
:lgtm_cancel: you need to update the apidsl file.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48#-:-KPYzUTPhiPBXDUrPtwt:b-ky75iv)*

**Comment by iphydf** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[testing/tox_shell.c, line 59 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/48#-KPZzJU_6PBSr2vL8vDU:-KPZzJU_6PBSr2vL8vDV:bu9iuo7) ([raw file](https://github.com/toktok/toxcore/blob/83d4857f080f6393ada976f3151bce5db2f96e23/testing/tox_shell.c#L59)):*
> ```C
>                    void *userdata)
> {
>     int master = *((int *)userdata);
> ```

This will now cause a null pointer dereference. You will want to pass the userdata `master` to `tox_iterate`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48)*

**Comment by GrayHatter** [comment]
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[testing/tox_shell.c, line 59 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/48#-KPZzJU_6PBSr2vL8vDU:-KP_6ckcyvTn8siJXKjK:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/83d4857f080f6393ada976f3151bce5db2f96e23/testing/tox_shell.c#L59)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This will now cause a null pointer dereference. You will want to pass the userdata `master` to `tox_iterate`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48)*

**Comment by iphydf** [comment]
:lgtm:

---

Reviewed 2 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48#-:-KP_7EnBiODWbN587Dkf:bnfp4nl)*

**Comment by iphydf** [comment]
Rebase, then I'll merge.

**Comment by iphydf** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/48#-:-KPd87ZJsYDerNNAe3Vd:bnfp4nl)*

**Pull request merged**
