### PR TITLE
Do not use `else` after `return`.

### PR DESCRIPTION
**Pull request by iphydf**
http://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/78)

### CODE REVIEW

**Comment by JFreegman** [comment]
:lgtm:

---

Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78#-:-KQaaOy7CTDde08FEVD3:bnfp4nl)*

**Comment by nurupo** [comment]
Reviewed 1 of 31 files at r1, 23 of 23 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[toxcore/DHT.c, line 2507 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcTEMdE7MGeMcvFxli:-KQcTEMeqx8rgzsnDkOX:b-gigwy2) ([raw file](https://github.com/toktok/toxcore/blob/79d6cc11e8f4fc5f558471d6d70f1ef5e2124bdb/toxcore/DHT.c#L2507)):*
> ```C
>             return dht->cryptopackethandlers[number].function(dht->cryptopackethandlers[number].object, source, public_key,
>                     data, len);
>         } /* If request is not for us, try routing it. */
> ```

Move the comment one line lower?

---

*[toxcore/net_crypto.c, line 1396 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcU3jvCkqUiW9RQHPV:-KQcU3jvCkqUiW9RQHPW:b23muxu) ([raw file](https://github.com/toktok/toxcore/blob/579bdc126f3054e27224b2b612eea52eb22e8507/toxcore/net_crypto.c#L1396)):*
> ```C
>         } else {
>             //TODO?
>         }
> ```

I think that `else` part has to stay for the 'TODO' to make sense.

---

*[toxcore/net_crypto.c, line 1543 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcULMqIxjYHpQ0rVHx:-KQcULMrBFhkMzY2n0zq:b-a582bc) ([raw file](https://github.com/toktok/toxcore/blob/579bdc126f3054e27224b2b612eea52eb22e8507/toxcore/net_crypto.c#L1543)):*
> ```C
>             }
> 
>             return 0;
> ```

That's interesting. Looks like some logic error with that unnecessary `return 0`, or someone just forgot to remove it while extending code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78)*

**Comment by nurupo** [comment]
Reviewed 7 of 31 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[toxcore/DHT.c, line 2507 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcTEMdE7MGeMcvFxli:-KQe3gB9_eikYK_cOhjs:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/79d6cc11e8f4fc5f558471d6d70f1ef5e2124bdb/toxcore/DHT.c#L2507)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Move the comment one line lower?
</details>
Done.

---

*[toxcore/net_crypto.c, line 1396 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcU3jvCkqUiW9RQHPV:-KQe3pmhizgw6OufoCZA:bkbd08q) ([raw file](https://github.com/toktok/toxcore/blob/579bdc126f3054e27224b2b612eea52eb22e8507/toxcore/net_crypto.c#L1396)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> I think that `else` part has to stay for the 'TODO' to make sense.
</details>
Does the TODO make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78)*

**Comment by nurupo** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/net_crypto.c, line 1396 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcU3jvCkqUiW9RQHPV:-KQeIfueBeaEeHIMS0aj:b-tv5d4b) ([raw file](https://github.com/toktok/toxcore/blob/579bdc126f3054e27224b2b612eea52eb22e8507/toxcore/net_crypto.c#L1396)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Does the TODO make sense?
</details>
Can't we just keep the `} else { // TODO? }`? It's not obvious that with `// else TODO?` you mean the `else` of the if-statement above, at least to me it's not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78)*

**Comment by iphydf** [comment]
Review status: 29 of 31 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/net_crypto.c, line 1396 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/78#-KQcU3jvCkqUiW9RQHPV:-KQeM7UXra21PprI5IAp:bmg28hl) ([raw file](https://github.com/toktok/toxcore/blob/579bdc126f3054e27224b2b612eea52eb22e8507/toxcore/net_crypto.c#L1396)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Can't we just keep the `} else { // TODO? }`? It's not obvious that with `// else TODO?` you mean the `else` of the if-statement above, at least to me it's not.
</details>
How about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/78#-:-KQeQPn0IKyvxcbEikf9:bnfp4nl)*

**Pull request merged**
