### PR TITLE
Add version-sync script.

### PR DESCRIPTION
**Pull request by iphydf**
This will update tox.in.h only. Currently, you will still need to
manually update tox.h. An upcoming PR (#154) will update tox.h as
part of the build.

### CODE REVIEW

**Comment by nurupo** [comment]
Doesn't changing the versions directly in the source files break the promise of out-of-tree building not to litter the source tree? e.g. if you build tox like `mkdir build && cd build && cmake ..` you probably don't expect it to go and modify the sources.

**Comment by iphydf** [comment]
This script won't change any source files unless you change the CMakeLists.txt file, in which case you break the promise yourself. This script just makes sure that if you change one place, the other places are also changed.

**Comment by nurupo** [comment]
I see, the source files would already have the versions set to the same values as in CMakeLists.txt file when someone git clones / gets a tarball, so changing them again to the same values would be a no-op.

**Comment by nurupo** [comment]
No patch commits :\

**Comment by GrayHatter** [comment]
@iphydf :shipit:

**Pull request merged**
