### PR TITLE
Apidsl fixes and start tracking test coverage

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/1)

### CODE REVIEW

**Comment by nurupo** [comment]
@iphydf any reason why @DeriveFH (https://github.com/irungentoo/toxcore/pull/1542) is not attributed for `Fixes for apidsl`?

**Comment by nurupo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 2 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1AA0_v6422HFcrazi:-KM1AA0aMDKQ_fbb6Vt1:-1342322644) ([raw file](https://github.com/toktok/toxcore/blob/532629d486e3361c7d8d95b38293cc7d61dc4ee5/.travis.yml#L2)):*
> ```YAML
> sudo: required
> dist: trusty
> ```

Why are we switching Travis away from using Ubuntu 14.04 to Ubuntu 12.04? https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

Ubuntu 14.04 has libconfig-dev, libvpx-dev, libopus-dev and check in it's package repos, which eliminates all the building you do below in this file.

---

*[.travis.yml, line 17 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1DV3hJEIUjLChjpht:-KM1CyVoMhjpnubzNK7_:-67517475) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L17)):*
> ```YAML
> cache:
>   directories:
>     - $HOME/cache
> ```

Hm, you want to cache all the builds to save time it takes for Travis to run? It looks okay.

---

*[.travis.yml, line 73 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1Bo23sJq0uoxC8LnH:-KM1Bo23sJq0uoxC8LnI:-1039659973) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L73)):*
> ```YAML
>         cd ..
>       }
>   - popd
> ```

Most of this building is not necessary if Ubuntu 14.04 is used.

---

*[.travis.yml, line 90 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1BZaGxTNwWHJ_sOIj:-KM1BZaGxTNwWHJ_sOIk:-1357237028) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L90)):*
> ```YAML
>         CFLAGS="-O0 -Wall -Wextra -fprofile-arcs -ftest-coverage"
>   - make
>   - make check || true
> ```

Doesn't Travis already fail a build if any of commands exit with non 0 code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1)*

**Comment by nurupo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 90 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1BZaGxTNwWHJ_sOIj:-KM1H8JlrgnGzs4RK0o6:792138115) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L90)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Doesn't Travis already fail a build if any of commands exit with non 0 code?
</details>
Ok, misread this. So, we ignore the exit code of the testing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1)*

**Comment by iphydf** [comment]
I didn't know that PR existed when I made my changes, but I'm happy to incorporate commits from there. I'll back out my changes.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 2 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1AA0_v6422HFcrazi:-KM1LSpq12NdF-bN_fIG:-697862418) ([raw file](https://github.com/toktok/toxcore/blob/532629d486e3361c7d8d95b38293cc7d61dc4ee5/.travis.yml#L2)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why are we switching Travis away from using Ubuntu 14.04 to Ubuntu 12.04? https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
> 
> Ubuntu 14.04 has libconfig-dev, libvpx-dev, libopus-dev and check in it's package repos, which eliminates all the building you do below in this file.
</details>
This is because sudo enabled builds don't support caching. It saves quite a lot of time to avoid building apidsl dependencies and libsodium every time.

---

*[.travis.yml, line 17 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1DV3hJEIUjLChjpht:-KM1Lo3AlAip37V6veLi:1461765252) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L17)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Hm, you want to cache all the builds to save time it takes for Travis to run? It looks okay.
</details>
Indeed.

---

*[.travis.yml, line 73 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1Bo23sJq0uoxC8LnH:-KM1LvGFJAAYf6SkI-HT:-1844991222) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L73)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Most of this building is not necessary if Ubuntu 14.04 is used.
</details>
Correct, but the building is mitigated by caching which is not available on 14.04.

---

*[.travis.yml, line 90 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1BZaGxTNwWHJ_sOIj:-KM1M3rGzrGzSSS5WCAG:1949157646) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L90)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Ok, misread this. So, we ignore the exit code of the testing?
</details>
Yes, we ignore test outcome because it fails. The first thing we need to do after this is to fix the test and stop ignoring its failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1#-:-KM1L5RZxKfX30hBCFJ0:1753543114)*

**Comment by nurupo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 73 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1Bo23sJq0uoxC8LnH:-KM1Ocl-dTo4UNbqcok0:-501747431) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L73)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Correct, but the building is mitigated by caching which is not available on 14.04.
</details>
This page says that caching is available in 14.04 https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

I guess whether it's available or not doesn't matter because the boot time for 14.04 is way slower than for the container 12.04.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1)*

**Comment by iphydf** [comment]
@yashikno I've merged your changes here. Thanks for making them.

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 73 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/1#-KM1Bo23sJq0uoxC8LnH:-KM4GG8jB_Dlvt4HaSV9:1407593162) ([raw file](https://github.com/toktok/toxcore/blob/071b4b3eed0040904de3f9aaf63f4ee31de2f5ae/.travis.yml#L73)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> This page says that caching is available in 14.04 https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
> 
> I guess whether it's available or not doesn't matter because the boot time for 14.04 is way slower than for the container 12.04.
</details>
Amended the commit message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1)*

**Comment by nurupo** [comment]
How/where is the 60% of code coverage enforced?

**Comment by iphydf** [comment]
Unfortunately, that is currently only set on the coveralls settings page. I hope to get codecov.io submission working at some point, and then the setting is in a codecov.yml file.

**Comment by nurupo** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/1)*

**Comment by nurupo** [comment]
Hm, reviewable shows me a "Merge & Retain Branch", which is interesting as I shouldn't have permissions to push into this repo.

**Comment by nurupo** [comment]
Yet GitHub says 
dfdfsdf

I guess reviewable doesn't check if I have permission until I try to merge through its web UI and GitHub API returns an error.

**Pull request merged**
