### PR TITLE
Fix plane size calculation in test

### PR DESCRIPTION
**Pull request by mannol**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/66)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm: thanks :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/66#-:-KQ7bc2w1fJ9wuUI9j09:beoh653)*

**Comment by iphydf** [comment]
:lgtm: now I know why it got stale: I assigned myself.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/66#-:-KQ7blFBcZ7msLRjTHtc:bvsueb2)*

**Comment by GrayHatter** [comment]
@mannol @iphydf  are we sure it should be /4 and not /2?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/66#-:-KQ9Ef3-omopiCw_O9dG:bz6iujp)*

**Comment by mannol** [comment]
@GrayHatter pretty sure. x/2 * y/2 = x*y/4

**Pull request merged**
