### PR TITLE
Enable build of av_test.

### PR DESCRIPTION
**Pull request by iphydf**
It has not been built in a while. We do want to keep this one working (or at
least compiling).

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/75)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 42 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/75#-KQTYHTPmjXTzSIMyWh6:-KQTYHTPmjXTzSIMyWh7:b-p7dtaz) ([raw file](https://github.com/toktok/toxcore/blob/95eae9e186b83152a6138d0bfc6697be60c4e5a9/CMakeLists.txt#L42)):*
> ```CMake
> pkg_search_module(OPUS      REQUIRED opus     )
> pkg_search_module(SNDFILE            sndfile  )
> pkg_search_module(VPX       REQUIRED vpx      )
> ```

I wonder if grouping them with comments would make CMakeLists.txt more friendly to whoever tries to look into it and understand why all of this is needed, e.g.

```cmake
# toxcore
pkg_search_module(LIBSODIUM REQUIRED libsodium)
# toxav
pkg_search_module(OPUS      REQUIRED opus     )
pkg_search_module(VPX       REQUIRED vpx      )
# tox-bootstrapd
pkg_search_module(LIBCONFIG          libconfig)
# tests
pkg_search_module(CHECK              check    )
# toxav tests
pkg_search_module(OPENCV             opencv   )
pkg_search_module(SNDFILE            sndfile  )
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75)*

**Comment by nurupo** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75)*

**Comment by nurupo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[testing/av_test.c, line 39 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/75#-KQTbXUP9_5YfsNSbs24:-KQTbXUP9_5YfsNSbs25:bw3et8p) ([raw file](https://github.com/toktok/toxcore/blob/95eae9e186b83152a6138d0bfc6697be60c4e5a9/testing/av_test.c#L39)):*
> ```C
> #include <opencv/cv.h>
> #include <opencv/highgui.h>
> #include <opencv/cvwimage.h>
> ```

Looks like build fails because these OpenCV headers are not found.
These headers are provided by [`libcv-dev`](http://packages.ubuntu.com/precise/libcv-dev) and [`libhighgui-dev`](http://packages.ubuntu.com/precise/libhighgui-dev) packages. These packages provide C API of OpenCV, while `libopencv-dev` provides C++ API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75#-:-KQTZXWNh4hdMqaP-7HX:bnfp4nl)*

**Comment by iphydf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 42 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/75#-KQTYHTPmjXTzSIMyWh6:-KQWxESHkrBgbjvVvSmx:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/95eae9e186b83152a6138d0bfc6697be60c4e5a9/CMakeLists.txt#L42)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> I wonder if grouping them with comments would make CMakeLists.txt more friendly to whoever tries to look into it and understand why all of this is needed, e.g.
> 
> ```cmake
> # toxcore
> pkg_search_module(LIBSODIUM REQUIRED libsodium)
> # toxav
> pkg_search_module(OPUS      REQUIRED opus     )
> pkg_search_module(VPX       REQUIRED vpx      )
> # tox-bootstrapd
> pkg_search_module(LIBCONFIG          libconfig)
> # tests
> pkg_search_module(CHECK              check    )
> # toxav tests
> pkg_search_module(OPENCV             opencv   )
> pkg_search_module(SNDFILE            sndfile  )
> ```
</details>
Done.

---

*[testing/av_test.c, line 39 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/75#-KQTbXUP9_5YfsNSbs24:-KQWxFv96TZsIPdsFAZc:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/95eae9e186b83152a6138d0bfc6697be60c4e5a9/testing/av_test.c#L39)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Looks like build fails because these OpenCV headers are not found.
> These headers are provided by [`libcv-dev`](http://packages.ubuntu.com/precise/libcv-dev) and [`libhighgui-dev`](http://packages.ubuntu.com/precise/libhighgui-dev) packages. These packages provide C API of OpenCV, while `libopencv-dev` provides C++ API.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75#-:-KQWyM2L0Wy7LcO5SsD-:bnfp4nl)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/75#-:-KQX0Hwf0Sd3sRu1zzWY:bnfp4nl)*

**Pull request closed without merging**
