### PR TITLE
Comment intentional switch fallthroughs

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/110)

### CODE REVIEW

**Comment by GrayHatter** [comment]
> Assigns me 
> then unassigns me (so I'll still get the notification spam)

Fuket, I'm reviewing it anyways.

IMO, the comments should be on the same line, not a new one.

:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR53CzHHAG7WNHyNAbv:bj1seco)*

**Comment by GrayHatter** [comment]
This fails the auto-style checks.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR53eAw2ERKQ-SGgdiH:bhb3vwt)*

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR5Rsgr59t1AQRCVTFm:bg7igkv)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 841 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/110#-KR5bPIF4vdXEgBPIJOA:-KR5bPIF4vdXEgBPIJOB:bu2tggi) ([raw file](https://github.com/toktok/toxcore/blob/b00a943beca51a58c80a4c1b43fb7d75a0440cd5/toxcore/Messenger.c#L841)):*
> ```C
>                               void *))
> {
>     callback_friendrequest(&(m->fr), (void ( *)(void *, const uint8_t *, const uint8_t *, size_t, void *))function, m);
> ```

Please undo this whitespace change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110)*

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR5bxIxR_MgmO-3zNL-:bg7igkv)*

**Comment by iphydf** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110)*

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR5cHCh487Qb8sMaDCG:bg7igkv)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110#-:-KR5dEyJfjY2BPmdCVcQ:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/110)*

**Pull request merged**
