### PR TITLE
4. Cmake

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/23)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewing so many PRs that have the same or very similar changes (the Travis script files) is getting quite annoying, hope at least one of them gets merged soon :/

**Comment by iphydf** [comment]
As soon as one of them gets LGTM, it'll be merged.

**Comment by iphydf** [comment]
I'll keep #20 open, so it can be independently merged.

**Comment by nurupo** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[other/bootstrap_daemon/src/config.h, line 42 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/23#-KOpLQLQZcCVoLu6xCJt:-KOpLQLSweGVNOglMPWc:bcmgg5j) ([raw file](https://github.com/toktok/toxcore/blob/fa6eeb460ecf0ee065e742ce6048e20952ebd071/other/bootstrap_daemon/src/config.h#L42)):*
> ```objc
> int get_general_config(const char *cfg_file_path, char **pid_file_path, char **keys_file_path, int *port,
>                        int *enable_ipv6,
>                        int *enable_ipv4_fallback, int *enable_lan_discovery, int *enable_tcp_relay, uint16_t **tcp_relay_ports,
> ```

Looks like astyle kept the new line where it shouldn't really be kept

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23)*

**Comment by nurupo** [comment]
Reviewed 17 of 18 files at r1.
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23)*

**Comment by iphydf** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[other/bootstrap_daemon/src/config.h, line 42 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/23#-KOpLQLQZcCVoLu6xCJt:-KOpRPEwapAx-3rFRhUB:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/fa6eeb460ecf0ee065e742ce6048e20952ebd071/other/bootstrap_daemon/src/config.h#L42)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Looks like astyle kept the new line where it shouldn't really be kept
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23)*

**Comment by nurupo** [comment]
Now that I have reached the meat of the PR, the CmakeLists.txt, I wonder

1. why do we change the build system
2. and even if there is some very good reason for changing it -- why it's not on the same feature parity than the old one
  - can't disable building toxav, toxdns
  - no option to enable building tox-bootstrapd
  - no option to do static build of the library
  - etc

**Comment by nurupo** [comment]
Hm, you also kept the "die autotools", but you test that to core build only with cake in Travis... I'm confused. If you want to have both, doesn't it make sense to test both of them?

**Comment by iphydf** [comment]
We don't really change it for now, we just add a new one and we'll develop it for a while until it does have feature parity. Reasons for changing it are:
- Maintaining the autotools build is going to cost more time than getting a new one.
- The autotools build is a little broken in that it doesn't use libsodium's pkg-config, and I really don't want to fix it (for the reason above).
- Building on other platforms natively will be easier with cmake.
- During development, ninja is a much better tool than make, making the developer experience a much more pleasant one.

I can add one extra build to exercise the autotools build.

---

Review status: 16 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23#-:-KOpRca03GT38TvpOgRD:b8zfn4o)*

**Comment by iphydf** [comment]
Done.

---

Review status: 14 of 23 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23#-:-KOpYVbwAFlvCuyGwghJ:b-896fix)*

**Comment by GrayHatter** [comment]
:lgtm: 

my exp with cmake is < good, someone else should look at CMakeLists.txt as well.

---

Reviewed 11 of 18 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/23#-:-KOwEGMjG6RNkIt_axo5:b-l1vwse)*

**Comment by tux3** [comment]
LGTM for the CMake part.

**Pull request merged**
