### PR TITLE
Add option to build static libraries.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/126)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/ModulePackage.cmake, line 48 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQNpuq6tjo1AviwxR4:-KRQNpur7J31pCFHuBb1:b-ebrdv3) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L48)):*
> ```CMake
>   endif()
> 
>   foreach(target ${_targets})
> ```

Is `_targets` a local variable, i.e. it gets cleaned on function exit, or it's a static variable, i.e. every time `target_link_modules` is ran, a single entry is added to `_targets`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126)*

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmake/ModulePackage.cmake, line 7 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQn4pgQYv8bf0YdAbl:-KRQn4phtcDlmSBGYbyb:b-ytfrjh) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L7)):*
> ```CMake
>   # shared libraries will result in multiple definition errors, since multiple
>   # tox libraries will link against libsodium and other libraries that are
>   # built statically in MXE.
> ```

Never heard of MXE and it doesn't sound all that good, so I don't like it, but if it's a quick and dirty way of hacking things into building Windows binary for Travis -- it's okay.

Anyway, this comment says that building shared libraries won't work with MXE. It doesn't say that building shared libraries won't work without MXE. So why do you assume everyone will use only MXE to build shared libraries and disable shared builds for all windows builds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126)*

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmake/ModulePackage.cmake, line 7 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQn4pgQYv8bf0YdAbl:-KRT6bCNzZJ4l7p7NXlr:bss4a2b) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L7)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Never heard of MXE and it doesn't sound all that good, so I don't like it, but if it's a quick and dirty way of hacking things into building Windows binary for Travis -- it's okay.
> 
> Anyway, this comment says that building shared libraries won't work with MXE. It doesn't say that building shared libraries won't work without MXE. So why do you assume everyone will use only MXE to build shared libraries and disable shared builds for all windows builds?
</details>
Removed.

---

*[cmake/ModulePackage.cmake, line 48 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQNpuq6tjo1AviwxR4:-KRT6GUAsvAdsgPdKenC:bdpwa7l) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L48)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Is `_targets` a local variable, i.e. it gets cleaned on function exit, or it's a static variable, i.e. every time `target_link_modules` is ran, a single entry is added to `_targets`?
</details>
It's a local variable. https://cmake.org/cmake/help/v3.0/command/function.html second to last paragraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/ModulePackage.cmake, line 48 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQNpuq6tjo1AviwxR4:-KRWeR2s64ADOtH4dq3V:b-hdb1lg) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L48)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> It's a local variable. https://cmake.org/cmake/help/v3.0/command/function.html second to last paragraph.
</details>
Then why do we iterate over `_targets` at that line? It looks like target can only be a single thing, not a list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/ModulePackage.cmake, line 48 at r1](https://reviewable.io:443/reviews/toktok/toxcore/126#-KRQNpuq6tjo1AviwxR4:-KRYgAXMOkB0SDJ5C0un:b-nwc9l4) ([raw file](https://github.com/toktok/toxcore/blob/4075d6a03b5221c8de36b2e509801c9017d8d717/cmake/ModulePackage.cmake#L48)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Then why do we iterate over `_targets` at that line? It looks like target can only be a single thing, not a list.
</details>
It can be either 1 or 2 things: ${target}_shared, ${target}_static, both of them, or ${target} if neither exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/126#-:-KRb8QtJC9j0GVB9XSyQ:b-jbsf8z)*

**Comment by GrayHatter** [comment]
removed myself as a reviewer because I don't know cmake well enough for my review to mean anything.

**Pull request closed without merging**
