### PR TITLE
Run hstox test suite against toxcore on Travis.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/16)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/16#-:-KM_IegCBYDvKC59hgOw:1417088721)*

**Comment by iphydf** [comment]
@nurupo this is a superset of #15. If you like, you can review only this one and I'll drop #15. I would not squash these commits, because the first change is good by itself.

**Comment by nbraud** [comment]
Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[other/travis/hstox-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNq_wk7RL0MGCnWYxP8:-KNq_wk7RL0MGCnWYxP9:-15502634) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-after_script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Why is this an empty script containing `set -e -x`?
Since it systematically succeeds on purpose, I think it would be less confusing to explicitly have `true` there instead.

---

*[other/travis/hstox-install, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqbdXkwUqZADptwg4W:-KNqbdXkwUqZADptwg4X:1551623081) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-install#L18)):*
> ```
> 
> cd hstox
> make configure
> ```

Only `configure`?
If this is on purpose, please add a comment why.

---

*[other/travis/hstox-script, line 6 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqaUA8c07NvkCgg_e0:-KNqaUA8c07NvkCgg_e1:-1513068720) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-script#L6)):*
> ```
> 
> cd ../hstox
> make check-toxcore
> ```

`make -C ../hstox check-toxcore`?
I could be the only one finding `${CWD}` changes in scripts confusing, but you use the `-C` idiom in other places too.

---

*[other/travis/toxcore-script, line 6 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqbMfatByG67kA_OKO:-KNqbMfatByG67kA_OKP:1315093100) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/toxcore-script#L6)):*
> ```
> 
> # Check if toxcore.h and toxav.h match apidsl tox.in.h and toxav.in.h.
> ../apidsl/_build/apigen.native ./other/apidsl/tox.in.h   | $ASTYLE --options=./other/astyle/astylerc > toxcore/tox.h
> ```

Why `astyle` here and `clang-format` [in hstox](https://github.com/TokTok/hstox/pull/48) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/16)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[other/travis/hstox-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNq_wk7RL0MGCnWYxP8:-KNrGSnb8Ntfy5tzqwf8:-1175896192) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-after_script#L3)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Why is this an empty script containing `set -e -x`?
> Since it systematically succeeds on purpose, I think it would be less confusing to explicitly have `true` there instead.
</details>
All scripts start with the same preamble. Currently, it always succeeds, but later it won't necessarily always succeed (when we start recording coverage).

---

*[other/travis/hstox-install, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqbdXkwUqZADptwg4W:-KNrFNCRfZshT83Fws8V:-499146009) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-install#L18)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Only `configure`?
> If this is on purpose, please add a comment why.
</details>
Done.

---

*[other/travis/hstox-script, line 6 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqaUA8c07NvkCgg_e0:-KNrFOaBg4C3-PhXD6ex:137506728) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/hstox-script#L6)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> `make -C ../hstox check-toxcore`?
> I could be the only one finding `${CWD}` changes in scripts confusing, but you use the `-C` idiom in other places too.
</details>
Done. In toxcore-install it's still required to chdir in some places, because `./configure` uses `$PWD`.

---

*[other/travis/toxcore-script, line 6 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KNqbMfatByG67kA_OKO:-KNrG7JhRNymPuvZCQHb:-1322570461) ([raw file](https://github.com/toktok/toxcore/blob/da8c5b423b55a3d8e452cd427d4ac80b282522cb/other/travis/toxcore-script#L6)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Why `astyle` here and `clang-format` [in hstox](https://github.com/TokTok/hstox/pull/48) ?
</details>
hstox and toxcore have different coding styles. hstox is going to use clang-format. Ideally, toxcore would also, but it's currently not useful to change all the formatting of toxcore. Why clang-format: it's more consistent in C and C++ and less buggy. Why astyle in toxcore: it was already astyled before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/16)*

**Comment by nurupo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 3 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODx4s0f84VHEywMA9N:-KODx4s0f84VHEywMA9O:-555441255) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/.travis.yml#L3)):*
> ```YAML
> language: c
> compiler:
>   - clang
> ```

Any particular reason for switching order from "gcc, clang" to "clang, gcc" or it was just an accidental change?

---

*[.travis.yml, line 22 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODxQyrrRbVztfY7778:-KODxQyrrRbVztfY7779:-1764696544) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/.travis.yml#L22)):*
> ```YAML
>       - libvpx-dev
>       - opam            # For apidsl and Frama-C.
>       - texinfo         # For libconfig.
> ```

How did it work without texinfo before? Why is it needed?

---

*[other/travis/toxcore-install, line 42 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODy2R4mKBQy-lCHTm2:-KODy2R4mKBQy-lCHTm3:-792433887) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/other/travis/toxcore-install#L42)):*
> ```
>   autoreconf -fi
>   ./configure --prefix=$CACHE_DIR
>   touch lib/scanner.l
> ```

Why is this `touch` needed? I know it's not a change made in this PR, but I didn't notice it before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/16)*

**Comment by iphydf** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 3 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODx4s0f84VHEywMA9N:-KOidxpNSyvcArLQ3Vz0:b-6s611d) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/.travis.yml#L3)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Any particular reason for switching order from "gcc, clang" to "clang, gcc" or it was just an accidental change?
</details>
Just sorting things. I like to keep unordered lists (where ordering doesn't matter) sorted. This is a publicly visible thing, on the travis build status page, so I like to have that sorted as well.

---

*[.travis.yml, line 22 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODxQyrrRbVztfY7778:-KOie8oi5nF-1ynf0XZu:b-il3myd) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/.travis.yml#L22)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> How did it work without texinfo before? Why is it needed?
</details>
It's needed for libconfig documentation. It doesn't look like it can be built without docs. I'm not sure why it worked before, but perhaps on the newer (14.04) build machine, texinfo is already installed.

---

*[other/travis/toxcore-install, line 42 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/16#-KODy2R4mKBQy-lCHTm2:-KOif9ll3cQvvKz6zAOp:b45xv4a) ([raw file](https://github.com/toktok/toxcore/blob/f478cb7e28c014d6ed46d0203933ecaad7aa58e4/other/travis/toxcore-install#L42)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why is this `touch` needed? I know it's not a change made in this PR, but I didn't notice it before.
</details>
Because the repo contains .c/.h files generated from scanner.l and they are broken (I forgot in what way). This forces make to call flex again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/16)*

**Pull request closed without merging**
