### PR TITLE
Add OSX and Windows build to travis config.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/61)

### CODE REVIEW

**Comment by nurupo** [comment]
*[other/astyle/format-source, line 19 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/61#-KQ8KDfJ_thMnp5aD8QQ:-KQ8KDfJ_thMnp5aD8QR:b-n7adt4) ([raw file](https://github.com/toktok/toxcore/blob/0bc0569cce294498f9540dc028f7a8d20b04fabf/other/astyle/format-source#L19)):*
> ```
> if ! which "$ASTYLE"; then
>   # If we couldn't find or install an astyle binary, don't do anything.
>   exit
> ```

Shouldn't that be `exit 1`? Travis uses this script, and if someone will be updating travis files and break them in such a way that Travis wouldn't find the astyle, this condition will make the Travis build succeed even though it skipped astyle and APIDSL checks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/61)*

**Comment by nurupo** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[other/travis/autotools-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/61#-KQ8LMOZFLMDmsugoim2:-KQ8LMO_bygbP__4HApN:b-dy01hc) ([raw file](https://github.com/toktok/toxcore/blob/a45356ce3eb14ad016732593cd5eedfd6f05df6f/other/travis/autotools-script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -u -x
> ```

Why were these options removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/61)*

**Comment by nurupo** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/61)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[other/astyle/format-source, line 19 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/61#-KQ8KDfJ_thMnp5aD8QQ:-KQAThOlH0EgvvlPuj4R:b-915xcd) ([raw file](https://github.com/toktok/toxcore/blob/0bc0569cce294498f9540dc028f7a8d20b04fabf/other/astyle/format-source#L19)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Shouldn't that be `exit 1`? Travis uses this script, and if someone will be updating travis files and break them in such a way that Travis wouldn't find the astyle, this condition will make the Travis build succeed even though it skipped astyle and APIDSL checks.
</details>
Yes, this was intentional, but I agree with you, so done.

---

*[other/travis/autotools-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/61#-KQ8LMOZFLMDmsugoim2:-KQATkzaO62c5nJKZSJk:b-92fqnh) ([raw file](https://github.com/toktok/toxcore/blob/a45356ce3eb14ad016732593cd5eedfd6f05df6f/other/travis/autotools-script#L3)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why were these options removed?
</details>
They are now in "phase", which sources the files instead of fork/execing them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/61)*

**Comment by iphydf** [comment]
Closing this one as well because coveralls shows 0% coverage. I'll investigate.

**Pull request closed without merging**
