### PR TITLE
7. Travis envs

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/31)

### CODE REVIEW

**Comment by iphydf** [comment]
Please comment on all files changed.

**Comment by GrayHatter** [comment]
Reviewed 2 of 17 files at r1.
Review status: 2 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[other/pkgconfig/toxav.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOwN01bBwIF4j9RgA_9:-KOwN01bBwIF4j9RgA_A:bxb2qkp) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxav.pc.in#L8)):*
> ```
> Description: Tox A/V library
> Requires: opus toxcore vpx
> Version: @PROJECT_VERSION@
> ```

is @PROJECT_VERSION@ going to be the ToxAV version, or the toxcore version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by GrayHatter** [comment]
Reviewed 14 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[other/travis/autotools-install, line 43 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOwOtxVn8e9RXYjpXlv:-KOwOtxWF5m_uLXdMrZF:bvpwrv9) ([raw file](https://github.com/toktok/toxcore/blob/926d7aa5771587dec67a235e6d1b9f68ae9fa27e/other/travis/autotools-install#L43)):*
> touch lib/scanner.l

what does this line do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by initramfs** [comment]
Reviewed 16 of 17 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 13 unresolved discussions.

---

*[.travis.yml, line 27 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxnTryzf4SIyW9D2dF:-KOxnTrzRV0dt6Vy285E:bmtp7ol) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/.travis.yml#L27)):*
> ```YAML
> cache:
>   directories:
>     - $HOME/.cabal
> ```

Not a particularly large issue given that it works, but travis docs explicitly state that the value of `$HOME` should not be relied on.

---

*[CMakeLists.txt, line 56 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxxjIach0jdt3mr4QU:-KOxxjIbTZZytE8uVWaY:b-csevuz) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L56)):*
> ```CMake
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${VPX_CFLAGS_OTHER}")
> 
> if(WIN32)
> ```

Just a suggestion, but allow other ways for a static binary to be produced (not just compiling for win32). Say a compile flag or something.

---

*[other/pkgconfig/toxav.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOwN01bBwIF4j9RgA_9:-KOxo-kCewvPQSYZflJl:bgxs3cb) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxav.pc.in#L8)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> is @PROJECT_VERSION@ going to be the ToxAV version, or the toxcore version?
</details>
In addition to that, perhaps explicitly make it clear by declaring it as `PROJECT_AV_VERSION` or `PROJECT_CORE_VERSION` or names of that liking.

---

*[other/pkgconfig/toxcore.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxt13lfeHf3q_hEZHg:-KOxt13lfeHf3q_hEZHh:b-3yrnde) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxcore.pc.in#L8)):*
> ```
> Description: Tox protocol library
> Requires: libsodium
> Version: @PROJECT_VERSION@
> ```

See my suggestion after GrayHatter's comment above regarding unambiguous version vars, not a big deal though.

---

*[other/pkgconfig/toxdns.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxtKk73TWIeEXmcPNF:-KOxtKk73TWIeEXmcPNG:bptkxzz) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxdns.pc.in#L8)):*
> ```
> Description: Tox DNS3 library
> Requires: toxcore
> Version: @PROJECT_VERSION@
> ```

See my suggestion after GrayHatter's comment above regarding unambiguous version vars.

---

*[other/pkgconfig/toxencryptsave.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxtLtS8xo9H5fuD7_N:-KOxtLtS8xo9H5fuD7_O:bptkxzz) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxencryptsave.pc.in#L8)):*
> ```
> Description: Tox block encryption library
> Requires: toxcore
> Version: @PROJECT_VERSION@
> ```

See my suggestion after GrayHatter's comment above regarding unambiguous version vars.

---

*[other/travis/autotools-script, line 21 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrx6OV0kcJhGAywRG:-KOxrx6OV0kcJhGAywRH:broet6g) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/autotools-script#L21)):*
> ```
> # do care whether it configures/builds at all, which is exercised by the make
> # call above. Tests are executed by the cmake build.
> make distcheck -j `nproc` || true
> ```

If this is to run, I suggest echoing at least a part of the comment above such that future log-dwellers don't get alarmed by this failure.

A simple

    echo "The following step may fail, see: <link to this line>

Or even better, if it fails (change to a if-condition) , print a clean "fail ignored" error message

---

*[other/travis/hstox-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqV_RX5rO7o9ejMHc:-KOxqV_SswqZtYNExLHM:bjwu6ht) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-after_script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

This can be changed to `set -e -u -x` to guard against uninitialized vars from being used. (I've tested a travis build with `-u`, doesn't seem to cause issues).

---

*[other/travis/hstox-install, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqc8VWk1rHo3RY2fV:-KOxqc8VWk1rHo3RY2fW:b-mv518n) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-install#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Same as above, change to `set -e -u -x`. Tested on travis.

---

*[other/travis/hstox-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqjyxNMg6nadv0fJD:-KOxqjyxNMg6nadv0fJE:b-mv518n) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Same as above, change to `set -e -u -x`. Tested on travis.

---

*[other/travis/toxcore-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrY8b-46GrPEt_4ck:-KOxrY8c1eLlKp_JNQWH:b-mv518n) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-after_script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Same as above, change to `set -e -u -x`. Tested on travis.

---

*[other/travis/toxcore-install, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrZ4Ssu5a1f4OC9So:-KOxrZ4Ssu5a1f4OC9Sp:b-mv518n) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-install#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Same as above, change to `set -e -u -x`. Tested on travis.

---

*[other/travis/toxcore-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxra0P3G4UOuuHH-3P:-KOxra0Qq8om-sWf2-5V:b-mv518n) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-script#L3)):*
> ```
> #!/bin/sh
> 
> set -e -x
> ```

Same as above, change to `set -e -u -x`. Tested on travis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by tux3** [comment]
Review status: 15 of 16 files reviewed at latest revision, 15 unresolved discussions.

---

*[CMakeLists.txt, line 60 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxvyKbv3NN1eEboI8H:-KOxvyKbv3NN1eEboI8I:bggkhjs) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L60)):*
> ```CMake
> else()
>   set(LIBTYPE SHARED)
> endif()
> ```

What's the rationale for this?
It could use a comment.

---

*[CMakeLists.txt, line 140 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxzYFwQdS9UCLBM6gc:-KOxzYFxtin9CsaMEBKb:b1qykyw) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L140)):*
> ```CMake
>   if(CHECK_FOUND)
>     add_executable(auto_${target} auto_tests/${target}.c)
>     target_link_libraries(auto_${target}
> ```

No toxdns, will it not have tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by initramfs** [comment]
Review status: 15 of 16 files reviewed at latest revision, 15 unresolved discussions.

---

*[CMakeLists.txt, line 60 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxvyKbv3NN1eEboI8H:-KOy0n_iwfOpPaidWSNk:b-vswk97) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L60)):*
<details><summary><i>Previously, tux3 (Tux3) wrote…</i></summary>
> What's the rationale for this?
> It could use a comment.
</details>
Probably to save Windows tox-based programs from DLL hell, but don't quote me on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by iphydf** [comment]
Review status: 15 of 16 files reviewed at latest revision, 15 unresolved discussions.

---

*[.travis.yml, line 27 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxnTryzf4SIyW9D2dF:-KOzV5tdgQu7qsOlNu5W:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/.travis.yml#L27)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Not a particularly large issue given that it works, but travis docs explicitly state that the value of `$HOME` should not be relied on.
</details>
Done.

---

*[CMakeLists.txt, line 56 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxxjIach0jdt3mr4QU:-KOzVrUbJSnqkQqk6ofE:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L56)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Just a suggestion, but allow other ways for a static binary to be produced (not just compiling for win32). Say a compile flag or something.
</details>
Done.

---

*[CMakeLists.txt, line 60 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxvyKbv3NN1eEboI8H:-KOzVsnA_0KgZnmgmS0y:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L60)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Probably to save Windows tox-based programs from DLL hell, but don't quote me on it.
</details>
Done.

---

*[CMakeLists.txt, line 140 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxzYFwQdS9UCLBM6gc:-KOzVvi4idk3Gpw6nbm_:b-8cq40b) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L140)):*
<details><summary><i>Previously, tux3 (Tux3) wrote…</i></summary>
> No toxdns, will it not have tests?
</details>
I don't know whether it will, but currently it has none, so there is no linking required. I don't know the future of toxdns and I'm not terribly interested in it right now. I'm also not going to extend these tests. The toktok testing project works differently.

---

*[other/pkgconfig/toxav.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOwN01bBwIF4j9RgA_9:-KOzWChko7H9EW7lgNFd:b-vybrcy) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxav.pc.in#L8)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> In addition to that, perhaps explicitly make it clear by declaring it as `PROJECT_AV_VERSION` or `PROJECT_CORE_VERSION` or names of that liking.
</details>
All versions are the same in a single build. I've added a comment to the cmake file.

---

*[other/pkgconfig/toxcore.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxt13lfeHf3q_hEZHg:-KOzWeAMDxygc_6VWCxI:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxcore.pc.in#L8)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> See my suggestion after GrayHatter's comment above regarding unambiguous version vars, not a big deal though.
</details>
Done.

---

*[other/pkgconfig/toxdns.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxtKk73TWIeEXmcPNF:-KOzWf7n395M1vRAwpra:bf2jc2t) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxdns.pc.in#L8)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> See my suggestion after GrayHatter's comment above regarding unambiguous version vars.
</details>
No need to put a comment on every instance of this. My abstract thought is developed enough to be able to infer that a comment applies to all instances.

---

*[other/pkgconfig/toxencryptsave.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxtLtS8xo9H5fuD7_N:-KOzWx20H_xYuxWr802U:b-q64pkt) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxencryptsave.pc.in#L8)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> See my suggestion after GrayHatter's comment above regarding unambiguous version vars.
</details>
See above.

---

*[other/travis/autotools-script, line 21 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrx6OV0kcJhGAywRG:-KOzXWs4uJAOL7jIJa8d:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/autotools-script#L21)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> If this is to run, I suggest echoing at least a part of the comment above such that future log-dwellers don't get alarmed by this failure.
> 
> A simple
> 
>     echo "The following step may fail, see: <link to this line>
> 
> Or even better, if it fails (change to a if-condition) , print a clean "fail ignored" error message
</details>
Done.

---

*[other/travis/hstox-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqV_RX5rO7o9ejMHc:-KOzXinOuEEgkX2hjKGg:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-after_script#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> This can be changed to `set -e -u -x` to guard against uninitialized vars from being used. (I've tested a travis build with `-u`, doesn't seem to cause issues).
</details>
Done.

---

*[other/travis/hstox-install, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqc8VWk1rHo3RY2fV:-KOzXjQxb6Q1Q2QzweX6:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-install#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Same as above, change to `set -e -u -x`. Tested on travis.
</details>
Done.

---

*[other/travis/hstox-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxqjyxNMg6nadv0fJD:-KOzXk36oWFlRfm8foNR:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/hstox-script#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Same as above, change to `set -e -u -x`. Tested on travis.
</details>
Done.

---

*[other/travis/toxcore-after_script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrY8b-46GrPEt_4ck:-KOzXkkYcPSvo5huGS6d:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-after_script#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Same as above, change to `set -e -u -x`. Tested on travis.
</details>
Done.

---

*[other/travis/toxcore-install, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxrZ4Ssu5a1f4OC9So:-KOzXlQWWef-iUtyWM9S:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-install#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Same as above, change to `set -e -u -x`. Tested on travis.
</details>
Done.

---

*[other/travis/toxcore-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxra0P3G4UOuuHH-3P:-KOzXm4sEZ6BH52Ps2yt:b-x268m) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-script#L3)):*
<details><summary><i>Previously, initramfs wrote…</i></summary>
> Same as above, change to `set -e -u -x`. Tested on travis.
</details>
Same as above: next time no need to copy-paste to every instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by zetok** [comment]
I only reviewed travis & scripts part, since I don't know about CMake or pkgconfig stuff.

Aside from what I've commented on, there are some inconsistencies with how number of build jobs is set – e.g. in `toxcore-install.sh` dependencies are compiled with
```
-j3
```
while in other places 
```
-j `nproc`
```
is used. Personally, I think that `-j$(nproc)` should be used instead of the above mentioned.

AFAIK using `$()` instead of backticks is preferable.

---

Reviewed 1 of 1 files at r3, 1 of 10 files at r5.
Review status: 7 of 16 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[other/travis/autotools-script, line 9 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzj1elNchZNyE6UC9v:-KOzj1elNchZNyE6UC9w:bsha1at) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L9)):*
> ```
> ./autogen.sh
> ./configure \
>   --with-libsodium-libs=$CACHE_DIR/lib \
> ```

`s,$CACHE_DIR/lib,$LD_LIBRARY_PATH,` ?

---

*[other/travis/autotools-script, line 10 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzjLPWfs-ebo6dZmzA:-KOzjLPWfs-ebo6dZmzB:bmv9idf) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L10)):*
> ```
> ./configure \
>   --with-libsodium-libs=$CACHE_DIR/lib \
>   --with-libsodium-headers=$CACHE_DIR/include \
> ```

Perhaps include dir also should be sourced in `env.sh`?

---

*[other/travis/autotools-script, line 15 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzio-EwLM5AQe4-zRt:-KOzio-EwLM5AQe4-zRu:bjku24b) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L15)):*
> ```
>   --enable-ntox
> 
> make -j `nproc`
> ```

if `env-$ENV.sh` is sourced, shouldn't `$MAKE` be used?

Same would go for other `*install.sh` and `*script.sh`, unless I misunderstood the purpose of sourcing `$MAKE`?

---

*[other/travis/env.sh, line 7 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzgqI9SAfIpH5_iHH1:-KOzgqIAEvSLslUC2_fo:bwpm6yr) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/env.sh#L7)):*
> ```Shell
> export OPAMROOT=$CACHE_DIR/.opam
> export LD_LIBRARY_PATH=$CACHE_DIR/lib
> export PKG_CONFIG_PATH=$CACHE_DIR/lib/pkgconfig
> ```

`s,$CACHE_DIR/lib/,$LD_LIBRARY_PATH/,` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KOzlSI4JjDOTQlhRLWZ:bbubfn7)*

**Comment by iphydf** [comment]
$() is bash-only. I like my shell scripts bourne compatible. As for -j3, good point. I've changed it.

---

Review status: 7 of 16 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[other/travis/autotools-script, line 9 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzj1elNchZNyE6UC9v:-KP-445dbNDwS-AeFY_v:b1k6xbp) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L9)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> `s,$CACHE_DIR/lib,$LD_LIBRARY_PATH,` ?
</details>
$LD_LIBRARY_PATH is not a single path, but rather a `:`-separated list of lookup paths like $PATH.

---

*[other/travis/autotools-script, line 10 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzjLPWfs-ebo6dZmzA:-KP-4GD9LOyg121AU_HE:b9gglby) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L10)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> Perhaps include dir also should be sourced in `env.sh`?
</details>
You mean like $INCLUDE_DIR? I would prefer not to have too many variables. The include dir should always be at $CACHE_DIR/include. It doesn't make sense to hide that behind another variable.

---

*[other/travis/autotools-script, line 15 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzio-EwLM5AQe4-zRt:-KP-4Y5fbETO8JlT1mkE:bgprx57) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/autotools-script#L15)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> if `env-$ENV.sh` is sourced, shouldn't `$MAKE` be used?
> 
> Same would go for other `*install.sh` and `*script.sh`, unless I misunderstood the purpose of sourcing `$MAKE`?
</details>
$MAKE is for cross compilation only.

---

*[other/travis/env.sh, line 7 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOzgqI9SAfIpH5_iHH1:-KP-4cuij3Rps2PYrpoX:b-q64pkt) ([raw file](https://github.com/toktok/toxcore/blob/bbb157dc97ede8472e60e7b73fd149a6d299abb0/other/travis/env.sh#L7)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> `s,$CACHE_DIR/lib/,$LD_LIBRARY_PATH/,` ?
</details>
See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP-3xDow9SJ4M42KA_Q:b2k5plu)*

**Comment by GrayHatter** [comment]
I think the naming scheme could be improved, but doesn't need to be.

---

Review status: 7 of 16 files reviewed at latest revision, 20 unresolved discussions.

---

*[CMakeLists.txt, line 140 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxzYFwQdS9UCLBM6gc:-KP-51IzFO9r12g3tYZz:bz17etm) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L140)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> I don't know whether it will, but currently it has none, so there is no linking required. I don't know the future of toxdns and I'm not terribly interested in it right now. I'm also not going to extend these tests. The toktok testing project works differently.
</details>
No toxdns will never get tests. ToxDNS is around for legacy support. And will be dropped as soon as we can replace it with something else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KOwPnKE9tqnmlbcVFmK:b-ctmi6n)*

**Comment by iphydf** [comment]
I use a very similar setup on qtox. My plan is to continue doing this for a bit and then extract common logic from both, fix a naming scheme, and make it a "travis-xenv" (cross compile environment) repository that is used by both.

---

Review status: 7 of 16 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP-6vYcfWl7_-i4AXDd:bsfncij)*

**Comment by zetok** [comment]
:lgtm: for what I've reviewed.

---

Reviewed 2 of 17 files at r1, 4 of 10 files at r5, 4 of 4 files at r6.
Review status: 15 of 16 files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP-7aAm3OOHqk9sl_Ii:b-f32jxi)*

**Comment by initramfs** [comment]
Review status: 15 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[other/pkgconfig/toxdns.pc.in, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxtKk73TWIeEXmcPNF:-KP-SYBSHq2lcMN1bRmz:b-eigr3d) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/pkgconfig/toxdns.pc.in#L8)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> No need to put a comment on every instance of this. My abstract thought is developed enough to be able to infer that a comment applies to all instances.
</details>
I'm just helping you flag down every instance, incase you missed one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by tux3** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 10 of 10 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP-XJ0CP1PDDon_5gSX:bnfp4nl)*

**Comment by GrayHatter** [comment]
*[CMakeLists.txt, line 60 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxvyKbv3NN1eEboI8H:-KP-iAIcvdj9A9Pd8W8j:b8sdlix) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/CMakeLists.txt#L60)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Done.
</details>
LGTM

It's because windows can't link sanely to save it's life.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by GrayHatter** [comment]
:lgtm:

Single non-blocking comment below on CMakeLists.txt

---

Reviewed 2 of 17 files at r1, 6 of 10 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[CMakeLists.txt, line 7 \[r6\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KP-jgifEol5E6j7E-Cq:-KP-jgigZiAQWCLUwtBQ:b-u11cda) ([raw file](https://github.com/toktok/toxcore/blob/35932b5381886f1d650d2cf853384273d080b821/CMakeLists.txt#L7)):*
> ```CMake
> # This version is for the entire project. All libraries (core, av, ...) move in
> # versions in a synchronised way.
> set(PROJECT_VERSION "0.0.0")
> ```

Non-blocking, but I'm interested in the rational for using a single "build version" instead of the version of each existing module. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP-k1QPiYgzVu-zF9e8:brqdker)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[CMakeLists.txt, line 7 \[r6\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KP-jgifEol5E6j7E-Cq:-KP2VQfKq0nOUX3hMTaW:bblfb55) ([raw file](https://github.com/toktok/toxcore/blob/35932b5381886f1d650d2cf853384273d080b821/CMakeLists.txt#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Non-blocking, but I'm interested in the rational for using a single "build version" instead of the version of each existing module. 
</details>
Because that's the way it currently is, and this PR is not about changing versioning schemes. We can talk about that another time. Feel free to open an issue to discuss versioning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31)*

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 6 of 10 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[other/travis/toxcore-script, line 3 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/31#-KOxra0P3G4UOuuHH-3P:-KP4MmqGR72jfrXUIVla:b-cs5xqj) ([raw file](https://github.com/toktok/toxcore/blob/e86d8de9319ed6fa1ba086e3d007bb698854813f/other/travis/toxcore-script#L3)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Same as above: next time no need to copy-paste to every instance.
</details>
Ok. Same thing, just helping you track down instances in Reviewable so you don't need to hunt for them in the repo. I deliberately didn't flag the autotools ones because I couldn't authenticate whether they would break anything (since the build was already failing due to distcheck).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/31#-:-KP4PP75NeNybWnI4wps:bnfp4nl)*

**Pull request merged**
