### PR TITLE
DHT addon

### PR DESCRIPTION
**Pull request by BoBeR182**
allows for 3rd party apps to harvest DHT info

---
This change is NOT reviewable. Use Github reviews instead.

### CODE REVIEW

**Comment by BoBeR182** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/93#-:-KQmZ8gP9J3ABpN72fv6:bg7igkv)*

**Comment by iphydf** [comment]
Can you make the callback stateless as described in #40? Also, the merge commit is empty, you can remove it.

**Comment by nurupo** [comment]
Do we want this in toxcore master?

**Comment by GrayHatter** [comment]
> Do we want this in toxcore master?

I don't think we do

**Comment by JFreegman** [comment]
This allows developers to leverage the DHT without using a third party implementation or having to write their own. On the other hand, it's not used by the core itself and is not required for typical client usage, so it could be considered unnecessary. Is low-level access to the DHT something we want toxcore supply to third parties? If so, this probably belongs in the public API. Right now it's written as a bit of a hack and doesn't really fit in anywhere.

**Comment by BoBeR182** [comment]
I feel that creating a low level DHT access to the network can be helpful for some clients that want finer control over statistics or who you set as bootstrap nodes. Developers having an easier time means better apps get developed and more user growth.

**Comment by GrayHatter** [comment]
I'm all for adding this as an undocumented, unsupported API. 

I'm not sure if this is the BEST way to go about it. But isn't not the worst way.

**Comment by iphydf** [comment]
My thoughts on this: #119

**Comment by iphydf** [comment]
Please discuss this change with irungentoo on the PR you made on his repo. If you have thoughts on #119, please post them there. You're very welcome to contribute ideas for a generalised DHT API that this callback could be part of.

**Pull request closed without merging**
