### PR TITLE
Make Friend User Status stateless

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/57)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 69 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/57#-KPe4QsN1gk94cjngGNW:-KPe4QsN1gk94cjngGNX:b7i7dyj) ([raw file](https://github.com/toktok/toxcore/blob/4d83451da6f478473c6519c3dccd7a60f32b3acf/.gitignore#L69)):*
> ```
> 
> # astyle
> *.orig
> ```

Removed because it breaks `git clean` and thereby grepping through files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/57)*

**Comment by nurupo** [comment]
:lgtm:

Don't understand the reasoning behind `.gitignore` though, don't use `git clean` and have no idea what grepping it breaks.

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/57#-:-KPemESvxzOpBIfpaTRD:bkjkqmd)*

**Comment by nurupo** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/57)*

**Comment by iphydf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/57#-:-KPlVzwAtSTwQHy5L2Mf:bnfp4nl)*

**Pull request merged**
