### PR TITLE
Added a rebase script

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/102)

### CODE REVIEW

**Comment by nurupo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[other/toktok-rebase, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/102#-KQwfV2Yjc7Tr5tNImPi:-KQwfV2Yjc7Tr5tNImPj:b-9ph4o9) ([raw file](https://github.com/toktok/toxcore/blob/593c56eb222fcdaccb249368b1c4b5937ed00f1d/other/toktok-rebase#L1)):*
> ```
> #!/usr/bin/zsh
> ```

If you write a script for everyone, which is what you do by adding it here, make it more portable than that, use `sh`.

```
#!/usr/bin/env sh
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/102)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[other/toktok-rebase, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/102#-KQwfV2Yjc7Tr5tNImPi:-KQwiHkMXcCIFRX3EPT4:b-4q0g7j) ([raw file](https://github.com/toktok/toxcore/blob/593c56eb222fcdaccb249368b1c4b5937ed00f1d/other/toktok-rebase#L1)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> If you write a script for everyone, which is what you do by adding it here, make it more portable than that, use `sh`.
> 
> ```
> #!/usr/bin/env sh
> ```
</details>
Builtin's are required that don't exist in sh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/102)*

**Comment by zetok** [comment]
>Builtin's are required that don't exist in sh.

use bash then

**Comment by nurupo** [comment]
>use bash then

We have a policy in toktok/toxcore to write things using `sh`.

You sure you can't do that is `sh`? Summoning @Encrypt

**Comment by zetok** [comment]
>We have a policy in toktok/toxcore to write things using `sh`.

Where is this listed?

**Comment by nurupo** [comment]
Do we have a list of policies?
```
<nurupo> iphy: is bash-ism something we want to avoid in toxcore shell scripts?
<nurupo> i kind of assumed it is, but we never discussed that
<nurupo> since not everyone uses bash
<iphy> nurupo: I'd like to avoid bash-isms, yes
```

**Comment by zetok** [comment]
That's not a policy, but a preference.

**Comment by GrayHatter** [comment]
No support for this script, y'allre on your own I guess

**Pull request closed without merging**
