### PR TITLE
Add getters/setters for options.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/72)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/72#-:-KQP3_QvccKJQy-C9ai4:bnfp4nl)*

**Comment by GrayHatter** [comment]
Has this been tested in any client?

Do any changes made be any of the fxns require the Tox instance to be restarted before they take effect?

Has that been tested in client?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/72#-:-KQPFGW551Icpl2M84Qc:b-3dbc5j)*

**Comment by GrayHatter** [comment]
Answered in IRC, I misunderstood the changes.

:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/72#-:-KQPHL3nK3pjzxPNBiRe:b-8vx7jg)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/72)*

**Comment by nurupo** [comment]
Might as well just make Tox_Options an opaque pointer type.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/72#-:-KQPHe4IDyHbjmaPf1YJ:b-50qiy7)*

**Pull request closed without merging**
