### PR TITLE
Make tox_callback_friend_name stateless.

### PR DESCRIPTION
**Pull request by iphydf**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/36)

### CODE REVIEW

**Comment by JFreegman** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPOZ4jpRL2zZS-Q9Ay6:bnfp4nl)*

**Comment by JFreegman** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36)*

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPOeARAqXMqlkicl71Q:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 24 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPPaym-yicOUDf8Zni4:bnfp4nl)*

**Comment by JFreegman** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPPdQsWYD54H5xwv4fE:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 3 of 32 files at r1, 8 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[other/travis/env-linux.sh, line 11 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPdnfHzLyiY_wkS629:-KPPdnfII3kHIXte-Ruy:b-5ywv6l) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/other/travis/env-linux.sh#L11)):*
> ```Shell
> export MAKE=make
> export PREFIX=$PWD/_install
> export NPROC=`nproc`
> ```

IF $TRAVIS NPROC=2?

---

*[other/travis/toxcore-script, line 15 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPcwaTHyByhxH1B-70:-KPPcwaUi2eDmYYz-srx:b-fshww1) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/other/travis/toxcore-script#L15)):*
> ```
> # Build toxcore and run tests.
> export CFLAGS="-O3 -fprofile-arcs -ftest-coverage -DTRAVIS_ENV=1"
> RUN $CMAKE -B$BUILD_DIR -H. -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -DLOGGING=ON -DDEBUG=ON
> ```

-DDEBUG vs -DTOX_DEBUG?

---

*[toxcore/DHT.c, line 2627 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPcehw9HYdPboN9F7r:-KPPcehxG6JKf2IpAIfp:bnl6b5l) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/toxcore/DHT.c#L2627)):*
> ```C
> #ifdef TOX_DEBUG
> 
>         default:
> ```

unrelated to this PR, but it's here anyway. Are we sure the default should be wrapped in the ifdef? As opposed to the content of the default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[other/travis/env-linux.sh, line 11 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPdnfHzLyiY_wkS629:-KPPeSeBW_Ce7maHUGPt:b-u0uxz9) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/other/travis/env-linux.sh#L11)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> IF $TRAVIS NPROC=2?
</details>
I think on travis `nproc` is in fact 2.

---

*[other/travis/toxcore-script, line 15 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPcwaTHyByhxH1B-70:-KPPeZc6X5YnPh60Yf0H:bha6cyr) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/other/travis/toxcore-script#L15)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> -DDEBUG vs -DTOX_DEBUG?
</details>
Yes, the cmake option is called DEBUG. It enables -DTOX_DEBUG in the C compiler, and may enable other things in the future.

---

*[toxcore/DHT.c, line 2627 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/36#-KPPcehw9HYdPboN9F7r:-KPPekt4VYXQZQp19sx6:b-1zs5j0) ([raw file](https://github.com/toktok/toxcore/blob/ff6c471b9ec1e95a094ec6ace47d80bbfa6dd2b9/toxcore/DHT.c#L2627)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> unrelated to this PR, but it's here anyway. Are we sure the default should be wrapped in the ifdef? As opposed to the content of the default?
</details>
It doesn't really matter. The ifdef could wrap only the `fprintf` or the whole `default` statement. Semantically, it's equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36)*

**Comment by nurupo** [comment]
Reviewed 14 of 32 files at r1, 1 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36)*

**Comment by nurupo** [comment]
Reviewed 14 of 32 files at r1, 5 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36)*

**Comment by JFreegman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPPrK_WbotLZiJqXmZ1:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 2 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPPtsXI2u-YMho7Y6Ca:bnfp4nl)*

**Comment by nurupo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/36#-:-KPPvTgS4EOcmfF3GY5M:bnfp4nl)*

**Pull request closed without merging**
