### PR TITLE
Split toxcore into layers.

### PR DESCRIPTION
**Pull request by iphydf**
This allows us to more clearly define interfaces between modules, and have the
linker help us ensure that module boundaries are respected.

The onion/tcp/net_crypto layer is a bit too large. This is due to a cyclic
dependency (onion -> net_crypto -> TCP -> onion). We may or may not want to
break that cycle in the future to allow the onion library to exist on its own
without net_crypto.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/34)

### CODE REVIEW

**Comment by nurupo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/34#-KPJ67O-w9S7JaLD4fMf:-KPJ67O-w9S7JaLD4fMg:b-h1zh7m) ([raw file](https://github.com/toktok/toxcore/blob/f788f11da6193cbdcef82e4ad5c05686becb7d06/CMakeLists.txt#L18)):*
> ```CMake
> set(CMAKE_MACOSX_RPATH ON)
> 
> add_definitions(-DTOX_LOGGER=1)
> ```

Do we want logging to be enabled by default?

Also, In case you didn't know, you can add generation-time options, like so

```cmake
option(LOGGING "Log things toxcore does" OFF)
if (LOGGING)
  set(LOGGING_PATH "NONE" CACHE PATH "Path to the directory where to put log files")
endif()
```

Then you use it as

```sh
cmake -DLOGGING=ON -DLOGGING_PATH=C:/toxcorelogs
```

The only issue with this is that re can't simply re-run cmake with changed options, the options get cached on the first run and re-running cmake doesn't invalidate the cache, you have to remove `CMakeCache.txt` if you want changed options to take effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/34)*

**Comment by iphydf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/34#-KPJ67O-w9S7JaLD4fMf:-KPJCYFS4bqG77k32_5Q:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/f788f11da6193cbdcef82e4ad5c05686becb7d06/CMakeLists.txt#L18)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Do we want logging to be enabled by default?
> 
> Also, In case you didn't know, you can add generation-time options, like so
> 
> ```cmake
> option(LOGGING "Log things toxcore does" OFF)
> if (LOGGING)
>   set(LOGGING_PATH "NONE" CACHE PATH "Path to the directory where to put log files")
> endif()
> ```
> 
> Then you use it as
> 
> ```sh
> cmake -DLOGGING=ON -DLOGGING_PATH=C:/toxcorelogs
> ```
> 
> The only issue with this is that re can't simply re-run cmake with changed options, the options get cached on the first run and re-running cmake doesn't invalidate the cache, you have to remove `CMakeCache.txt` if you want changed options to take effect.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/34)*

**Comment by nurupo** [comment]
Interesting how coverage for assoc.c has decreased just because the tests are not deterministic.

**Comment by nurupo** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/34)*

**Comment by nurupo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/34#-:-KPJNA0dwUiMVXDrINYY:bnfp4nl)*

**Comment by nurupo** [comment]
What happened to this PR?

**Comment by nurupo** [comment]
Oh, you merged it manually.

**Comment by iphydf** [comment]
I merged it using reviewable (it has a "fast forward" button). Apparently reviewable messed that one up.

**Pull request closed without merging**
