### PR TITLE
Apidsl test

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/49)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewed 3 of 3 files at r2.
Review status: 3 of 38 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 206 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/49#-KPekFguXWphKVLJeQXf:-KPekFguXWphKVLJeQXg:b-8o1eif) ([raw file](https://github.com/toktok/toxcore/blob/960db4f110372ddb839311561fbb66a25913a668/CMakeLists.txt#L206)):*
> ```CMake
> ################################################################################
> 
> add_test(format_test ${CMAKE_SOURCE_DIR}/other/astyle/format-source)
> ```

You could pass `${CMAKE_SOURCE_DIR}` to the shell script as an argument in `add_test()` and avoid the bashism (I assume you have changed it from `#!/bin/sh` to `#!/bin/bash` just for `${BASH_SOURCE[0]}`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 206 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/49#-KPekFguXWphKVLJeQXf:-KPtBX4b__K4hDso7RtR:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/960db4f110372ddb839311561fbb66a25913a668/CMakeLists.txt#L206)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> You could pass `${CMAKE_SOURCE_DIR}` to the shell script as an argument in `add_test()` and avoid the bashism (I assume you have changed it from `#!/bin/sh` to `#!/bin/bash` just for `${BASH_SOURCE[0]}`).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by nurupo** [comment]
Reviewed 38 of 38 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 206 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/49#-KPekFguXWphKVLJeQXf:-KPtDgpn41b21_hrLDLu:brgpfk) ([raw file](https://github.com/toktok/toxcore/blob/960db4f110372ddb839311561fbb66a25913a668/CMakeLists.txt#L206)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Done.
</details>
Huh, the new commit didn't show up as a new revision in the Reviewable, instead it showed up as r3, which I reviewwd just before you wrote Done and pushed in the commit.

Will check the new commit later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by nurupo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[other/astyle/format-source, line 5 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/49#-KPtnMH0nTKQgbWPa9ah:-KPtnMH0nTKQgbWPa9ai:baa0rzf) ([raw file](https://github.com/toktok/toxcore/blob/846d94d39ed295051f600eb07d456f8792801235/other/astyle/format-source#L5)):*
> ```
> set -e
> 
> SOURCE_DIR=$1
> ```

The lack of quotation marks around `$1`,  `$SOURCE_DIR` in `cd $SOURCE_DIR` and `${CMAKE_SOURCE_DIR}` in CMakeLists.txt  disturbs me. Will this script do what it is supposed to do if `${CMAKE_SOURCE_DIR}` contains spaces?

During last year's GSoC my student couldn't make the CMake project open in QtCreator properly, which apparently was caused by the project path having spaces in it. Took us a day to figure this out, and we managed to do that only by chance, because the student has included the command output textbox of Qt Creator in a screenshot, which allowed me to notice the spaces and ask to move the project somewhere with no spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by iphydf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[other/astyle/format-source, line 5 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/49#-KPtnMH0nTKQgbWPa9ah:-KPvhdxCzs7qwT99RRvw:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/846d94d39ed295051f600eb07d456f8792801235/other/astyle/format-source#L5)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> The lack of quotation marks around `$1`,  `$SOURCE_DIR` in `cd $SOURCE_DIR` and `${CMAKE_SOURCE_DIR}` in CMakeLists.txt  disturbs me. Will this script do what it is supposed to do if `${CMAKE_SOURCE_DIR}` contains spaces?
> 
> During last year's GSoC my student couldn't make the CMake project open in QtCreator properly, which apparently was caused by the project path having spaces in it. Took us a day to figure this out, and we managed to do that only by chance, because the student has included the command output textbox of Qt Creator in a screenshot, which allowed me to notice the spaces and ask to move the project somewhere with no spaces.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/49#-:-KPx9-i5iNQlSWjpxsi_:bnfp4nl)*

**Pull request merged**
