### PR TITLE
Update sysvinit docs for toktok fork

### PR DESCRIPTION
**Pull request by LittleVulpix**
Update the manual to provide a command necessary to open <1024 ports for users on SysVinit

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/10)

### CODE REVIEW

**Comment by GrayHatter** [comment]
@nurupo

**Comment by nurupo** [comment]
Eh... do i have to write the same comment in two repos now?

>What does `epi` stand for? I see some people using just `ep` for this, so I'm wondering. --nurupo

**Comment by LittleVulpix** [comment]
@nurupo :



    Capability Sets

    Each thread has three capability sets containing zero or more of the above capabilities:

    Effective - the capabilities used by the kernel to perform permission checks for the thread.

    Permitted - the capabilities that the thread may assume (i.e., a limiting superset for the effective and inheritable sets). If a thread drops a capability from its permitted set, it can never re-acquire that capability (unless it exec()s a set-user-ID-root program).

    inheritable - the capabilities preserved across an execve(2). A child created via fork(2) inherits copies of its parent's capability sets. See below for a discussion of the treatment of capabilities during exec(). Using capset(2), a thread may manipulate its own capability sets, or, if it has the CAP_SETPCAP capability, those of a thread in another process.

**Comment by nurupo** [comment]
Well, looks good to me. There is better way of doing that, directly in C code, but I don't have time for that and this is good enough.

**Comment by nurupo** [comment]
Hm, now i see why the high-five bot is useful. You can't access reviewable if you are not assigned to the issue.

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/10)*

**Comment by GrayHatter** [comment]
@nurupo you mean @iphydf

**Comment by nurupo** [comment]
>@nurupo you mean @iphydf

Welp, highlighted the wrong person. Thanks, fixed.

Also, now I can access reviewable. Did someone change something for it to work?

**Comment by iphydf** [comment]
Can you squash the commits? It's not very interesting in the history that you rebased on master.

**Comment by LittleVulpix** [comment]
see #11

**Pull request closed without merging**
