### PR TITLE
This is not right place to check for length

### PR DESCRIPTION
**Pull request by piling**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/5)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/crypto_core.c, line 89 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMGLHA6H7brPmeBpDgu:-KMGLHA6H7brPmeBpDgv:-920724844) ([raw file](https://github.com/toktok/toxcore/blob/41415ad626a14e1fd556a31a618b142ed415c495/toxcore/crypto_core.c#L89)):*
> ```C
>     if (!secret_key || !nonce || !plain || !encrypted)
>         return -1;
> ```

add here

assert(length > 0);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/crypto_core.c, line 89 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMGLHA6H7brPmeBpDgu:-KMG_4DDepVU0zz4zLS5:428086598) ([raw file](https://github.com/toktok/toxcore/blob/41415ad626a14e1fd556a31a618b142ed415c495/toxcore/crypto_core.c#L89)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> add here
> 
> assert(length > 0);
</details>
@jfreegman: The [article](http://blog.regehr.org/archives/1091) you linked to in PR #6 is in favour of this change. Why did you link to it?

**"An assertion is a Boolean expression at a specific point in a program which will be true unless there is a bug in the program."**

This is true for this change. The encrypt_data_symmetric function has no reason to require a non-zero length for its argument. `crypto_box` encrypts empty strings just fine. The only reason this check is here is a defence-in-depth validation of the higher layers which ought to never try to encrypt empty strings. The spec currently mentions [some reasons](https://toktok.github.io/spec#ping-service-3) why, but could be clearer.

Clearly there is no reason for encrypt_data_symmetric to make this check as part of the contract, since without it, it does the right thing for every valid input. Artificially adding non-emptyness constraints to the contract here is the wrong thing to do. However, since in reality we don't want to encrypt empty strings, and doing so would be a bug in a higher layer, a defence-in-depth approach, which is highly desirable for security software, mandates that we do checks at many layers, including the lowest one handling the crypto primitive. Because of this, I recommended removing the check from the conditional and replacing it with something like `assert`. Whether that should be the C standard library macro or a toxcore-specific macro is up for discussion. Important is that all the non-contract sanity checks can be disabled for testing purposes, so the test framework can check whether the code does the right thing for the entirety of its function domain.

If we want to make this check in production builds, I would recommend aborting the program when it happens. Silently handling a severe bug like this as a -1 that (hopefully) gets propagated up to some user level does not seem wise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by JFreegman** [comment]
@iphydf That is a retroactive rationalization for that commit, and it only makes sense in the context of a core-wide paradigm shift in regards to error handling. Arbitrarily replacing a boundary check with an assert in one function is inconsistent at the very least.

**Comment by iphydf** [comment]
This change came out of a discussion we had while implementing tests for toxcore. I recommended the removal and replacement with something else. The something else is as I said up for discussion. Perhaps this PR is a good forum for discussing the error handling in core. If you would like to take it somewhere else, I'm happy to move.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5#-:-KMGguMl0KFcrc8GsmQW:-176852134)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/crypto_core.c, line 108 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMKfIObIYekoMxrd-DO:-KMKfIObIYekoMxrd-DP:-419651818) ([raw file](https://github.com/toktok/toxcore/blob/23fd76e5b94e278afb6b2eb502bc02eab80743e8/toxcore/crypto_core.c#L108)):*
> ```C
>                            uint8_t *plain)
> {
>     if (length < crypto_box_BOXZEROBYTES || !secret_key || !nonce || !encrypted || !plain)
> ```

This will need an assert as well, if `assert` is the macro we want to use here. @jfreegman for input.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/crypto_core.c, line 89 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMGLHA6H7brPmeBpDgu:-KML1qJ1mnhmbmIhfkrB:213087990) ([raw file](https://github.com/toktok/toxcore/blob/41415ad626a14e1fd556a31a618b142ed415c495/toxcore/crypto_core.c#L89)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> @jfreegman: The [article](http://blog.regehr.org/archives/1091) you linked to in PR #6 is in favour of this change. Why did you link to it?
> 
> **"An assertion is a Boolean expression at a specific point in a program which will be true unless there is a bug in the program."**
> 
> This is true for this change. The encrypt_data_symmetric function has no reason to require a non-zero length for its argument. `crypto_box` encrypts empty strings just fine. The only reason this check is here is a defence-in-depth validation of the higher layers which ought to never try to encrypt empty strings. The spec currently mentions [some reasons](https://toktok.github.io/spec#ping-service-3) why, but could be clearer.
> 
> Clearly there is no reason for encrypt_data_symmetric to make this check as part of the contract, since without it, it does the right thing for every valid input. Artificially adding non-emptyness constraints to the contract here is the wrong thing to do. However, since in reality we don't want to encrypt empty strings, and doing so would be a bug in a higher layer, a defence-in-depth approach, which is highly desirable for security software, mandates that we do checks at many layers, including the lowest one handling the crypto primitive. Because of this, I recommended removing the check from the conditional and replacing it with something like `assert`. Whether that should be the C standard library macro or a toxcore-specific macro is up for discussion. Important is that all the non-contract sanity checks can be disabled for testing purposes, so the test framework can check whether the code does the right thing for the entirety of its function domain.
> 
> If we want to make this check in production builds, I would recommend aborting the program when it happens. Silently handling a severe bug like this as a -1 that (hopefully) gets propagated up to some user level does not seem wise.
</details>
@piling please add an empty line around this assert? I'd like things like that to be clearly seperated from prod code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/crypto_core.c, line 89 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMGLHA6H7brPmeBpDgu:-KMQGlhcg7zbFik0o4Q1:-2000023422) ([raw file](https://github.com/toktok/toxcore/blob/41415ad626a14e1fd556a31a618b142ed415c495/toxcore/crypto_core.c#L89)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> @piling please add an empty line around this assert? I'd like things like that to be clearly seperated from prod code.
</details>
Done.  @grayhatter

---

*[toxcore/crypto_core.c, line 108 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMKfIObIYekoMxrd-DO:-KMQGtJeO7V5bQ0inYfZ:4039616) ([raw file](https://github.com/toktok/toxcore/blob/23fd76e5b94e278afb6b2eb502bc02eab80743e8/toxcore/crypto_core.c#L108)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This will need an assert as well, if `assert` is the macro we want to use here. @jfreegman for input.
</details>
Done.  we decided to use macro instead, at least for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by neduard** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[toxcore/crypto_core.c, line 108 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMKfIObIYekoMxrd-DO:-KMQMPraqsCSP-qjLBp5:-387265687) ([raw file](https://github.com/toktok/toxcore/blob/23fd76e5b94e278afb6b2eb502bc02eab80743e8/toxcore/crypto_core.c#L108)):*
<details><summary><i>Previously, piling wrote…</i></summary>
> Done.  we decided to use macro instead, at least for now.
</details>
Why the extra compare in the `if` statement though?

---

*[toxcore/util.h, line 33 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQQnkhoEFe9L2A2vdY:-KMQQnkjHl_xtQT6R5bn:-2047322054) ([raw file](https://github.com/toktok/toxcore/blob/ac2af7c74d1d5a4505553388fffb67b42ca11772/toxcore/util.h#L33)):*
> ```objc
> 
> #if DISABLE_CHECKS
> #define return_val_if_fail(cond, val) do {} while (0)
> ```

Might be just me, but the "if fail" part generally adds extra mental work for people reading code. Can we name this using positive words (in the same way "assert" is not called "exit_if_fail")?

---

*[toxcore/util.h, line 35 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQRcRF6hOznfVu_Ca7:-KMQRcRGwjDHz2Cch2Jy:-1755790271) ([raw file](https://github.com/toktok/toxcore/blob/c1f450a3845ad265441758f8b7decb2c7fd8297e/toxcore/util.h#L35)):*
> ```objc
> #define return_val_if_fail(cond, val) do {} while (0)
> #else
> #define return_val_if_fail(cond, val) if (!(cond)) return val
> ```

WARNING: never write code in a macro outside a `do {} while (0)` statement.
Otherwise the code:
```
if (pointer != NULL)
   return_val_if_fail(another_check_on(pointer->member));
else
  authenticate();
```
Will be prime target for pesky NSA :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by GrayHatter** [comment]
*[toxcore/util.h, line 33 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQSPgNdD5EnpLGWC3L:-KMQSPgNdD5EnpLGWC3M:-1815022882) ([raw file](https://github.com/toktok/toxcore/blob/c1f450a3845ad265441758f8b7decb2c7fd8297e/toxcore/util.h#L33)):*
> ```objc
> 
> #if DISABLE_CHECKS
> #define return_val_if_fail(cond, val) do {} while (0)
> ```

MACROS must be all uppercase, in toxcore.

with an expection of alias for other fxn.

All uppercase signals, that compiler options will change how this section of works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[toxcore/util.h, line 33 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQQnkhoEFe9L2A2vdY:-KMQSjDHMcrh3g4jte2B:2125712729) ([raw file](https://github.com/toktok/toxcore/blob/ac2af7c74d1d5a4505553388fffb67b42ca11772/toxcore/util.h#L33)):*
<details><summary><i>Previously, neduard (Eduard Nicodei) wrote…</i></summary>
> Might be just me, but the "if fail" part generally adds extra mental work for people reading code. Can we name this using positive words (in the same way "assert" is not called "exit_if_fail")?
</details>
IMO macros should use single letter vars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by nurupo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[toxcore/crypto_core.c, line 108 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMKfIObIYekoMxrd-DO:-KMSH0eDWKCiurl2njvw:1950915386) ([raw file](https://github.com/toktok/toxcore/blob/23fd76e5b94e278afb6b2eb502bc02eab80743e8/toxcore/crypto_core.c#L108)):*
<details><summary><i>Previously, neduard (Eduard Nicodei) wrote…</i></summary>
> Why the extra compare in the `if` statement though?
</details>
So, why not

```C
return_val_if_fail(length > crypto_box_BOXZEROBYTES && secret_key && nonce && encrypted && plain, -1);
```

and remove the

```C
if (length < crypto_box_BOXZEROBYTES || !secret_key || !nonce || !encrypted || !plain)
    return -1;
```

part?

---

*[toxcore/util.h, line 33 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQQnkhoEFe9L2A2vdY:-KMSFYJeLtDLlr60p1x1:1618858661) ([raw file](https://github.com/toktok/toxcore/blob/ac2af7c74d1d5a4505553388fffb67b42ca11772/toxcore/util.h#L33)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> IMO macros should use single letter vars.
</details>
`ASSERT_RETURN` or its lower case variant would probably make a bit more sense. It tells that the semantics is that same as of assert, plus we have additional argument for the return value, in case assertion fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[toxcore/crypto_core.c, line 108 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMKfIObIYekoMxrd-DO:-KMTZM7crXdvXZYA1spD:-822607220) ([raw file](https://github.com/toktok/toxcore/blob/23fd76e5b94e278afb6b2eb502bc02eab80743e8/toxcore/crypto_core.c#L108)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> So, why not
> 
> ```C
> return_val_if_fail(length > crypto_box_BOXZEROBYTES && secret_key && nonce && encrypted && plain, -1);
> ```
> 
> and remove the
> 
> ```C
> if (length < crypto_box_BOXZEROBYTES || !secret_key || !nonce || !encrypted || !plain)
>     return -1;
> ```
> 
> part?
</details>
[Rationale](https://github.com/TokTok/toxcore/issues/8#issuecomment-231836827).

---

*[toxcore/util.h, line 33 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQQnkhoEFe9L2A2vdY:-KMTZWNOlTFEU7CjblcI:2056679782) ([raw file](https://github.com/toktok/toxcore/blob/ac2af7c74d1d5a4505553388fffb67b42ca11772/toxcore/util.h#L33)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> `ASSERT_RETURN` or its lower case variant would probably make a bit more sense. It tells that the semantics is that same as of assert, plus we have additional argument for the return value, in case assertion fails.
</details>
The semantics are not the same as `assert`. This macro will never terminate your program (unless you have a side-effect in the macro argument).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[toxcore/util.h, line 33 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQQnkhoEFe9L2A2vdY:-KMfBkayyFaxBxv-JxAL:5173665) ([raw file](https://github.com/toktok/toxcore/blob/ac2af7c74d1d5a4505553388fffb67b42ca11772/toxcore/util.h#L33)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> The semantics are not the same as `assert`. This macro will never terminate your program (unless you have a side-effect in the macro argument).
</details>
OK

---

*[toxcore/util.h, line 35 \[r5\]](https://reviewable.io:443/reviews/toktok/toxcore/5#-KMQRcRF6hOznfVu_Ca7:-KMfC2qNvUcdA4OU5Afn:1031638101) ([raw file](https://github.com/toktok/toxcore/blob/c1f450a3845ad265441758f8b7decb2c7fd8297e/toxcore/util.h#L35)):*
<details><summary><i>Previously, neduard (Eduard Nicodei) wrote…</i></summary>
> WARNING: never write code in a macro outside a `do {} while (0)` statement.
> Otherwise the code:
> ```
> if (pointer != NULL)
>    return_val_if_fail(another_check_on(pointer->member));
> else
>   authenticate();
> ```
> Will be prime target for pesky NSA :P
</details>
@neduard this is resolved, pls OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/5)*

**Comment by iphydf** [comment]
Since this PR is no longer being updated, I will close it for now. Please open a new PR after discussing on IRC.

**Pull request closed without merging**
