### PR TITLE
Rearrange fields to decrease size of structure

### PR DESCRIPTION
**Pull request by isotoxin**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/94)

### CODE REVIEW

**Comment by GrayHatter** [comment]
How much of an benefit is this?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/94#-:-KQnojGVHlVzoMF7wgYr:b-cvyu4k)*

**Comment by iphydf** [comment]
This change to `TCP_Secure_Connection` brings it down from from 12784 bytes to 11816 (saving 968 bytes) on LP64. The most significant saving comes from the `connections` array, because the padding is repeated 240 times. The outer `status` reordering saves 8 bytes.

By the way, `Crypto_Connection` in `net_crypto.c` is wasting 52 bytes with padding. It's fairly insignificant, however, because `Crypto_Connection` is 525416 bytes on LP64.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/94#-:-KQpQCZgdRI836cE3zOs:bmyj0nx)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/network.h, line 47 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/94#-KQq-mNaaX3WEGALc2cD:-KQq-mNaaX3WEGALc2cE:bnm3nix) ([raw file](https://github.com/toktok/toxcore/blob/43cd83ea5edb84aff1cfe33127b71bb4b864a6e8/toxcore/network.h#L47)):*
> ```objc
> #endif
> #include <winsock2.h>
> #include <windows.h>
> ```

This is not related to field order. Please make a separate PR, and put a comment here explaining why the include order matters (ideally with a link to supporting documentation). Also put a newline (or that comment) between the two includes, so that formatters won't reorder them again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/94)*

**Comment by isotoxin** [comment]
Sorry guys for second commit. I dont know how to make different PR's for different commits.
And about order: main rule of network programming under windows is: include winsock2.h before windows.h, or you get compile error

**Comment by iphydf** [comment]
You can make separate PRs by making separate git branches. Put a comment and link on your reordering. Is there no official documentation about this?

**Comment by iphydf** [comment]
The [example](https://msdn.microsoft.com/en-us/library/ms737629(VS.85).aspx) on MSDN shows windows.h being included before winsock2.h. There are some comments about include order, but they are about iphlpapi.h.

**Comment by isotoxin** [comment]
I just removed second commit.

**Comment by nurupo** [comment]
:lgtm:

> By the way, Crypto_Connection in net_crypto.c is wasting 52 bytes with padding. It's fairly insignificant, however, because Crypto_Connection is 525416 bytes on LP64.

Wow, `Crypto_Connection` is 513 KB?! It is a big structure, but it didn't look that big. Good to know.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/94#-:-KQssghFbv1ZZRp8-3lf:bjfxi0z)*

**Pull request merged**
