### PR TITLE
Remove unused and bit-rotten friends_test.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/76)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/76#-:-KQWaArAiOzRFUEiRLZl:bnfp4nl)*

**Comment by nurupo** [comment]
@iphydf bit-rotten?

**Comment by nurupo** [comment]
Do we have tests that test the same thing? Otherwise a replacement is needed.

**Comment by iphydf** [comment]
This test has not passed since at least August 2013, probably before. `tox_test` covers all the things that this test does.

**Pull request merged**
