### PR TITLE
Add braces to all if statements.

### PR DESCRIPTION
**Pull request by iphydf**
Also, removed friends_test, since it's been unused for a long time, and porting it to new internal APIs is not worth it.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/73)

### CODE REVIEW

**Comment by JFreegman** [comment]
:lgtm:

---

Reviewed 53 of 53 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/73#-:-KQRam3eXTNA5nyvTJ6M:bnfp4nl)*

**Comment by nurupo** [comment]
Reviewed 53 of 53 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[testing/DHT_test.c, line 218 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTeO-XOmrBVQRQ8aEf:-KQTeO-XOmrBVQRQ8aEg:by8wlow) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/DHT_test.c#L218)):*
> ```C
> 
> 
>     }
> ```

2 many empty lines.

---

*[testing/dns3_test.c, line 82 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTelxiwEUjW5PZgSk7:-KQTelxiwEUjW5PZgSk8:bdgs4wg) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/dns3_test.c#L82)):*
> ```C
> 
>     uint32_t request_id;
> ```

Why empty lines?

---

*[testing/irc_syncbot.c, line 151 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTey43yT5L11wVO4J3:-KQTey43yT5L11wVO4J4:b1eek13) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/irc_syncbot.c#L151)):*
> ```C
>             sendbuf[i] = ' ';
> 
>         }
> ```

Empty lines again.

---

*[testing/Messenger_test.c, line 182 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTfF_GsvvGkVjlBgqw:-KQTfF_GsvvGkVjlBgqx:brqm2nb) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/Messenger_test.c#L182)):*
> ```C
> 
> 
>     }
> ```

Empty lines.

---

*[toxav/video.c, line 149 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQThwKOk5_KgEA_5gyL:-KQThwKOk5_KgEA_5gyM:b-f8ohuo) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxav/video.c#L149)):*
> ```C
> 
>     struct RTPMessage *p;
> ```

Random new line introduction.

---

*[toxcore/Messenger.c, line 1187 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTurGUhgE4AaKdpi-V:-KQTurGUhgE4AaKdpi-W:bfpk8tw) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxcore/Messenger.c#L1187)):*
> ```C
> 
>     ft->paused = FILE_PAUSE_NOT;
> ```

New lines again.

---

*[toxcore/network.c, line 315 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTyc1OX8Cp5h9dNoy5:-KQTyc1P1rW_XhWqBmRk:b-50mmam) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxcore/network.c#L315)):*
> ```C
> 
>     struct sockaddr_storage addr;
> ```

Empty line again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/73)*

**Comment by iphydf** [comment]
Review status: 41 of 52 files reviewed at latest revision, 7 unresolved discussions.

---

*[testing/DHT_test.c, line 218 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTeO-XOmrBVQRQ8aEf:-KQX2Q1nttVh1-DrL1il:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/DHT_test.c#L218)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> 2 many empty lines.
</details>
Done.

---

*[testing/dns3_test.c, line 82 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTelxiwEUjW5PZgSk7:-KQX2QqnJQhyf1EQpEMn:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/dns3_test.c#L82)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why empty lines?
</details>
Done.

---

*[testing/irc_syncbot.c, line 151 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTey43yT5L11wVO4J3:-KQX2RepJilOk64I63oO:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/irc_syncbot.c#L151)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Empty lines again.
</details>
Done.

---

*[testing/Messenger_test.c, line 182 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTfF_GsvvGkVjlBgqw:-KQX2SOAUvt-Yy_ui3KU:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/testing/Messenger_test.c#L182)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Empty lines.
</details>
Done.

---

*[toxav/video.c, line 149 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQThwKOk5_KgEA_5gyL:-KQX2TXngVAolPeGw1Oy:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxav/video.c#L149)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Random new line introduction.
</details>
Done.

---

*[toxcore/Messenger.c, line 1187 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTurGUhgE4AaKdpi-V:-KQX2UJ23Il64p3QVMPk:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxcore/Messenger.c#L1187)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> New lines again.
</details>
Done.

---

*[toxcore/network.c, line 315 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/73#-KQTyc1OX8Cp5h9dNoy5:-KQX2V12s50vQI4gYhoN:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/6d51eaad7d636f12ca8b3c0c5df7e97c196d5ad0/toxcore/network.c#L315)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Empty line again.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/73)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/73#-:-KQX6AYsRnlI5KcRkxeo:bnfp4nl)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 2 of 13 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/73#-:-KQXBjrlscVAuU7QXNgh:bnfp4nl)*

**Pull request closed without merging**
