### PR TITLE
1. Move toxcore travis build scripts out of .travis.yml.

### PR DESCRIPTION
**Pull request by iphydf**
This is in preparation for having multiple types of build. One of the future
builds will be a hstox build, another may be frama-c or some other static
analyser. It makes sense to split these up into multiple builds, because each of
them can take a while, and running them in parallel will speed things up. Also,
the hstox test coverage should be reported separately from the toxcore auto_test
coverage.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/29)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[other/travis/toxcore-install, line 15 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvpJtbKs0pMfYrL6xJ:-KOvpJtbKs0pMfYrL6xK:b-u3aanw) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-install#L15)):*
> ```
> 
> # Build apidsl.
> git clone --depth=1 https://github.com/iphydf/apidsl
> ```

do we want to cache this as well, then we can git pull.

For this it's very low gain, but others will likely use it as an example when adding new sections

---

*[other/travis/toxcore-install, line 28 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp_jxhxAtjg-kqH62:-KOvp_jxhxAtjg-kqH63:b45sxk8) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-install#L28)):*
> ```
> }
> 
> # Install libsodium (not in ubuntu-precise).
> ```

I'm surprised Travis doesn't have this available to install. Did you check?

---

*[other/travis/toxcore-script, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp-eIY21CEbKALThN:-KOvp-eJYmL4Fq3N-SSm:be460xu) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-script#L18)):*
> ```
>   --enable-logging \
>   --enable-ntox \
>   CFLAGS="-O0 -Wall -Wextra -fprofile-arcs -ftest-coverage"
> ```

missing the TRAVIS_ENV define

---

*[other/travis/toxcore-script, line 21 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp6X1nKiVc5f_4_oI:-KOvp6X1nKiVc5f_4_oJ:b-stqx4h) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-script#L21)):*
> ```
> 
> make
> make check || true
> ```

not anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/29)*

**Comment by iphydf** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[other/travis/toxcore-install, line 15 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvpJtbKs0pMfYrL6xJ:-KOvqKbbFecfzX5cGBpl:bpfeefm) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-install#L15)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> do we want to cache this as well, then we can git pull.
> 
> For this it's very low gain, but others will likely use it as an example when adding new sections
</details>
No, I don't think we should ever cache git checkouts. It will clutter the cache for no gain. We use --depth=1 on all git clones, so we always only get the most recent version. Cloning any git repo takes a few seconds. Caching it would add complexity that is not warranted by the potential tiny gain in some situations.

---

*[other/travis/toxcore-install, line 28 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp_jxhxAtjg-kqH62:-KOvqfagZvYRul5eD90c:b-bsj9ep) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-install#L28)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> I'm surprised Travis doesn't have this available to install. Did you check?
</details>
It is in the debian-sid repo. I have never successfully installed anything from that repo, so I didn't try. Since we already build a bunch of things here, risking breakage due to debian-sid being unstable is not worth it.

---

*[other/travis/toxcore-script, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp-eIY21CEbKALThN:-KOvr-nLD8KwfT_2A9hH:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-script#L18)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> missing the TRAVIS_ENV define
</details>
Done.

---

*[other/travis/toxcore-script, line 21 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvp6X1nKiVc5f_4_oI:-KOvr0Np-2k3p59DUN4k:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-script#L21)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> not anymore
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/29)*

**Comment by iphydf** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[other/travis/toxcore-install, line 15 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/29#-KOvpJtbKs0pMfYrL6xJ:-KOvrCCZYXncBN0-7lcD:b-uu57sh) ([raw file](https://github.com/toktok/toxcore/blob/88ceb0267a5ed5d29b8179039d9c228460ba447e/other/travis/toxcore-install#L15)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> No, I don't think we should ever cache git checkouts. It will clutter the cache for no gain. We use --depth=1 on all git clones, so we always only get the most recent version. Cloning any git repo takes a few seconds. Caching it would add complexity that is not warranted by the potential tiny gain in some situations.
</details>
Ah, what would in fact help is caching apidsl itself. Either way, this PR is mostly about moving script from one place to another. We can think about that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/29)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/29#-:-KOvtsNYlyk3MBqi0Okx:bnfp4nl)*

**Pull request closed without merging**
