### PR TITLE
Separate ip_port packing from pack_nodes() and unpack_nodes()

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/109)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/DHT.c, line 377 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR4MNCC_eMWfGyZ_HuB:-KR4MNCC_eMWfGyZ_HuC:b-fyjxw0) ([raw file](https://github.com/toktok/toxcore/blob/5169f038980023e81fba7093d7c626750c5b71eb/toxcore/DHT.c#L377)):*
> ```C
> 
>         memcpy(data + packed_length, nodes[i].public_key, crypto_box_PUBLICKEYBYTES);
>         packed_length += crypto_box_PUBLICKEYBYTES;
> ```

Perhaps add an `assert` to check that the packed length is increased by either `PACKED_NODE_SIZE_IP6` or `PACKED_NODE_SIZE_IP4` in each iteration. I can statically verify it, but I like defensive checks :).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/109)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/DHT.c, line 30 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR5TLhPNTCgjnlrwT2-:-KR5TLhPNTCgjnlrwT20:b-ny64qc) ([raw file](https://github.com/toktok/toxcore/blob/86aaa84fc280d1f6b18a94a685326a7d1153f660/toxcore/DHT.c#L30)):*
> ```C
> #endif
> 
> #ifdef TOX_DEBUG
> ```

Remove the ifdef.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/109)*

**Comment by nurupo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[toxcore/DHT.c, line 30 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR5TLhPNTCgjnlrwT2-:-KR6_iOUPnqFCMGHJLv2:bbkpovk) ([raw file](https://github.com/toktok/toxcore/blob/86aaa84fc280d1f6b18a94a685326a7d1153f660/toxcore/DHT.c#L30)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove the ifdef.
</details>
Are you talking about `#ifdef TOX_DEBUG`? Well, it doesn't make much sense for you to talk about `#ifdef HAVE_CONFIG_H`, so I assume it's about `#ifdef TOX_DEBUG`. See the image if you wonder why I'm asking,



---

*[toxcore/DHT.c, line 240 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR6auqOoIuXMZzz1KXu:-KR6auqOoIuXMZzz1KXv:b-pyfo6g) ([raw file](https://github.com/toktok/toxcore/blob/7b01790fd63720b2479270749ae47ab32acdf908/toxcore/DHT.c#L240)):*
I'd do it a bit differently. I'd require the `data` pointer passed into `pack_ip_port()` to be already advanced to the position of where you want this function to pack the `IP_Port`, you'd also need to adjust the passed `length` accordingly. So, instead of 

>here is a data pointer, but please don't write directly at it, write at data+packed_length

it would be

>here is a pointer to where I want you to write the stuff

---

*[toxcore/DHT.c, line 282 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR6d_OK3OI3DO9OCsQ6:-KR6d_OK3OI3DO9OCsQ7:btctysb) ([raw file](https://github.com/toktok/toxcore/blob/7b01790fd63720b2479270749ae47ab32acdf908/toxcore/DHT.c#L282)):*
> ```C
>         data[packed_length] = net_family;
>         memcpy(data + packed_length + 1, &ip_port->ip.ip6, SIZE_IP6);
>         memcpy(data + packed_length + 1 + SIZE_IP6, &ip_port->port, sizeof(uint16_t));
> ```

Not of scope of this PR, but such `memcpy()` pattern is used in quite a few place in toxcore. What about writing some `Data_Packer` thing that takes an existing `uin8_t` array and allows to append all sorts of data to it easily, keeping track of the current offset? It would be a lot nicer in C++ than in C, with templates (even recursive variadic templates) and overloads, but it's still would provide some convenience even in C and prevent possible copy-paste errors.

So, instead of writing something like this 

```C
int foo(uint8_t *data, uint16_t length)
{
    uint8_t  a = 0;
    uint16_t b = 1;
    uint32_t c = 2;
    uint64_t d = 3;

    if (length < data + sizeof(a) + sizeof(b) + sizeof(c)) {
        fail;
    }

    memcpy(data,                                     a, sizeof(a));
    memcpy(data + sizeof(a),                         b, sizeof(b));
    memcpy(data + sizeof(a) + sizeof(b),             c, sizeof(c));
    memcpy(data + sizeof(a) + sizeof(b) + sizeof(c), d, sizeof(d));

    return data + sizeof(a) + sizeof(b) + sizeof(c);
}
```

You could write something like that in C

```C
int foo(uint8_t *data, uint16_t length)
{
    uint8_t  a = 0;
    uint16_t b = 1;
    uint32_t c = 2;
    uint64_t d = 3;

    Data_Packer packer = packer_init(data, length);

    // assumes uint8_t alignment of `a`, `b`, `c` and `d`
    pack_as_uint8t_arr(&a, sizeof(a));
    pack_as_uint8t_arr(&b, sizeof(b));
    pack_as_uint8t_arr(&c, sizeof(c));
    pack_as_uint8t_arr(&d, sizeof(d));

    // maybe you could check return value of `pack_as_uint8t_arr` instead
    if (paker.ok(&packer) != SUCCESS) {
        fail;
    }
    
    return packer_offset(&packer);
}
```

In C++ you could even do

```C++
int foo(uint8_t *data, uint16_t length)
{
    uint8_t  a = 0;
    uint16_t b = 1;
    uint32_t c = 2;
    uint64_t d = 3;

    Data_Packer packer(data, length);

    // doesn't assume any alignment, powered by variadic templates and overloads
    packer.pack(a, b, c, d);

    // maybe you could check return value of `Data_Packer::pack` instead
    if (!packer) {
        fail;
    }
    
    return packer.offset;
}
```

Something similar could be done to unpack things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/109)*

**Comment by iphydf** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[toxcore/DHT.c, line 30 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR5TLhPNTCgjnlrwT2-:-KR9iUCrUgtre6wrRrFh:b-odbz2b) ([raw file](https://github.com/toktok/toxcore/blob/86aaa84fc280d1f6b18a94a685326a7d1153f660/toxcore/DHT.c#L30)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Are you talking about `#ifdef TOX_DEBUG`? Well, it doesn't make much sense for you to talk about `#ifdef HAVE_CONFIG_H`, so I assume it's about `#ifdef TOX_DEBUG`. See the image if you wonder why I'm asking,
> 
> 
> 
</details>
Yes, it was about TOX_DEBUG. It's done.

---

*[toxcore/DHT.c, line 282 \[r3\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR6d_OK3OI3DO9OCsQ6:-KR9k7XSHGTl30JfJaNb:b-4xghcy) ([raw file](https://github.com/toktok/toxcore/blob/7b01790fd63720b2479270749ae47ab32acdf908/toxcore/DHT.c#L282)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Not of scope of this PR, but such `memcpy()` pattern is used in quite a few place in toxcore. What about writing some `Data_Packer` thing that takes an existing `uin8_t` array and allows to append all sorts of data to it easily, keeping track of the current offset? It would be a lot nicer in C++ than in C, with templates (even recursive variadic templates) and overloads, but it's still would provide some convenience even in C and prevent possible copy-paste errors.
> 
> So, instead of writing something like this 
> 
> ```C
> int foo(uint8_t *data, uint16_t length)
> {
>     uint8_t  a = 0;
>     uint16_t b = 1;
>     uint32_t c = 2;
>     uint64_t d = 3;
> 
>     if (length < data + sizeof(a) + sizeof(b) + sizeof(c)) {
>         fail;
>     }
> 
>     memcpy(data,                                     a, sizeof(a));
>     memcpy(data + sizeof(a),                         b, sizeof(b));
>     memcpy(data + sizeof(a) + sizeof(b),             c, sizeof(c));
>     memcpy(data + sizeof(a) + sizeof(b) + sizeof(c), d, sizeof(d));
> 
>     return data + sizeof(a) + sizeof(b) + sizeof(c);
> }
> ```
> 
> You could write something like that in C
> 
> ```C
> int foo(uint8_t *data, uint16_t length)
> {
>     uint8_t  a = 0;
>     uint16_t b = 1;
>     uint32_t c = 2;
>     uint64_t d = 3;
> 
>     Data_Packer packer = packer_init(data, length);
> 
>     // assumes uint8_t alignment of `a`, `b`, `c` and `d`
>     pack_as_uint8t_arr(&a, sizeof(a));
>     pack_as_uint8t_arr(&b, sizeof(b));
>     pack_as_uint8t_arr(&c, sizeof(c));
>     pack_as_uint8t_arr(&d, sizeof(d));
> 
>     // maybe you could check return value of `pack_as_uint8t_arr` instead
>     if (paker.ok(&packer) != SUCCESS) {
>         fail;
>     }
>     
>     return packer_offset(&packer);
> }
> ```
> 
> In C++ you could even do
> 
> ```C++
> int foo(uint8_t *data, uint16_t length)
> {
>     uint8_t  a = 0;
>     uint16_t b = 1;
>     uint32_t c = 2;
>     uint64_t d = 3;
> 
>     Data_Packer packer(data, length);
> 
>     // doesn't assume any alignment, powered by variadic templates and overloads
>     packer.pack(a, b, c, d);
> 
>     // maybe you could check return value of `Data_Packer::pack` instead
>     if (!packer) {
>         fail;
>     }
>     
>     return packer.offset;
> }
> ```
> 
> Something similar could be done to unpack things.
</details>
I like the idea of a packer/unpacker abstraction. Alternatively, we could increment the pointer itself, and compare with an end-pointer (like iterators) to see if we have enough space. That way, you also don't need to add more and more numbers together for the next memcpy call (which is as you correctly noted, error-prone).

---

*[toxcore/DHT.c, line 382 \[r4\]](https://reviewable.io:443/reviews/toktok/toxcore/109#-KR9jVh3skpRxq3w-Dw2:-KR9jVh3skpRxq3w-Dw3:b-bjqfkm) ([raw file](https://github.com/toktok/toxcore/blob/dd309374af60a6e4eb640e6ec5601c47912bb000/toxcore/DHT.c#L382)):*
> ```C
>         packed_length += crypto_box_PUBLICKEYBYTES;
> 
>         uint32_t increment = ipp_size + crypto_box_PUBLICKEYBYTES;
> ```

Alternatively, save packed_length at the beginning of the iteration and compare with the end. Currently, you have the addition twice, so if someone changes something in between, this increment assignment needs to be updated. If you just do `before - after == 4 or 6`, this doesn't need to be updated, and (imo) expresses the intent a bit more clearly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/109#-:-KR9kc_sBp5rfwAolQeS:bg7igkv)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/109#-:-KRCakLl9E1sDgyUAB0F:b-jbsf8z)*

**Pull request merged**
