### PR TITLE
Fix readme for TokTok

### PR DESCRIPTION
**Pull request by GrayHatter**
@iphydf

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/12)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/12#-KMQnZ1yI9nlrb78Jcep:-KMQnZ1yI9nlrb78Jceq:-252511063) ([raw file](https://github.com/toktok/toxcore/blob/903c39f8e83261e7fad16b8cd7c52c9ccaecd5b1/README.md#L4)):*
> ```Markdown
> ***
> 
> **Current build status:** [Build Status](https://travis-ci.org/TokTok/toxcore)
> ```

Can you also add the coverage status? See https://raw.githubusercontent.com/TokTok/hstox/master/README.md for an example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/12)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/12#-KMQnleXgX5ylLxkho7W:-KMQnleXgX5ylLxkho7X:-156611281) ([raw file](https://github.com/toktok/toxcore/blob/903c39f8e83261e7fad16b8cd7c52c9ccaecd5b1/README.md#L1)):*
> ```Markdown
> Project Tox
> ```

This could also be changed, in case someone decides to contribute a different logo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/12)*

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/12#-KMQnleXgX5ylLxkho7W:-KMQpYWtDDqlA-TiEM_9:-499146009) ([raw file](https://github.com/toktok/toxcore/blob/903c39f8e83261e7fad16b8cd7c52c9ccaecd5b1/README.md#L1)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This could also be changed, in case someone decides to contribute a different logo.
</details>
Done.

---

*[README.md, line 4 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/12#-KMQnZ1yI9nlrb78Jcep:-KMQp_Lxxuqz0kBtlby_:-499146009) ([raw file](https://github.com/toktok/toxcore/blob/903c39f8e83261e7fad16b8cd7c52c9ccaecd5b1/README.md#L4)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Can you also add the coverage status? See https://raw.githubusercontent.com/TokTok/hstox/master/README.md for an example.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/12)*

**Comment by nurupo** [comment]
LGTM, unless you want to fix IRC and other links.

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 5 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/12#-KMTDGs8pdphT9AmStMW:-KMTDGs8pdphT9AmStMX:-837924861) ([raw file](https://github.com/toktok/toxcore/blob/b03c8fdda97ddc363f257530ba8dd0a62e4e6027/README.md#L5)):*
> ```Markdown
> 
> **Current build status:** [Build Status](https://travis-ci.org/TokTok/toxcore)
> **Current Coverage :** [Coverage Status](https://coveralls.io/github/TokTok/toxcore?branch=master)
> ```

Remove the extra space before ':'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/12)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/12)*

**Pull request merged**
