### PR TITLE
make the majority of the callbacks stateless and add some status to a testcase

### PR DESCRIPTION
**Pull request by cleverca22**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/120)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[auto_tests/tox_test.c, line 662 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/120#-KREGinfXHvLsQSDoFVB:-KREGinfXHvLsQSDoFVC:b-a2zjlq) ([raw file](https://github.com/toktok/toxcore/blob/31602278cd205fc1c35bccbf3f50753141abd46b/auto_tests/tox_test.c#L662)):*
> ```C
>         tox_iterate(tox1, &to_compare);
>         tox_iterate(tox2, &to_compare);
>         tox_iterate(tox3, &packet_number);
> ```

Note to other reviewers: this is incorrect (but safe, it has the same type as `to_compare`) in theory. In practice, it works. Let's not focus on test code quality right now though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120#-:-KREIpXfzpz9GvtsmKfc:b-jbsf8z)*

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120#-:-KRE_KJqIIGaI3U-ZPti:b-jbsf8z)*

**Comment by JFreegman** [comment]
Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120)*

**Comment by nurupo** [comment]
Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[auto_tests/tox_test.c, line 925 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/120#-KRG0gfIHgUzsIDxgkCA:-KRG0gfJyjrKy_u9DAe2:b-1zekes) ([raw file](https://github.com/toktok/toxcore/blob/32c7ea6a36c1d9c954943acc87ccc5aefa03b9a4/auto_tests/tox_test.c#L925)):*
> ```C
> 
>         if (counter != last_count) {
>             printf("got to %d\n", counter);
> ```

Shouldn't that be `%u` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120#-:-KRG7cEfhYaXVeP-4Jnn:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/120#-:-KRHmVLc-ueGwy0pjeWL:b-jbsf8z)*

**Pull request merged**
