### PR TITLE
Fix windows build.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/44)

### CODE REVIEW

**Comment by nurupo** [comment]
Not sure what was broken and why this fixes it. Also don't know what is the purpose of those `_PKGCONFIG_LIBS` variables. Also don't know how to build toxcore with cmake to test if this PR actually fixes the building.

**Comment by iphydf** [comment]
Added comment to the code and more explanation to the commit message.

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/44#-:-KPeqU9QH9ku9HLZ1ugB:bnfp4nl)*

**Comment by iphydf** [comment]
@nurupo, I rebased; PTAL.

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/44#-:-KPj1XXYNXgbF0atKOzc:bnfp4nl)*

**Pull request closed without merging**
