### PR TITLE
Use "phase" script for travis build phases.

### PR DESCRIPTION
**Pull request by iphydf**
This is the first step towards unifying travis configs for toxcore,
hstox, and qtox.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/127)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/toktok/toxcore/127#-KRQ4jLZQqwtfivPMRKB:-KRQ4jLZQqwtfivPMRKC:b-4s0f1e) ([raw file](https://github.com/toktok/toxcore/blob/d038854bb9b82deaf82a95016fcd3577bdd11bf3/.travis.yml#L5)):*
> ```YAML
> matrix:
>   include:
>     - env: BUILD=hstox ENV=linux
> ```

This is called $BUILD here, but $JOB in phase, one should be renamed.

---

*[other/travis/phase, line 13 at r1](https://reviewable.io:443/reviews/toktok/toxcore/127#-KRQ4a42jGptvx682AKb:-KRQ4a43OWymlWO2sOnh:b469xef) ([raw file](https://github.com/toktok/toxcore/blob/d038854bb9b82deaf82a95016fcd3577bdd11bf3/other/travis/phase#L13)):*
> ```
> 
> try_source() {
>   SCRIPT="other/travis/$1"
> ```

Should we not use `${JOB}` here instead of  $1 to make it more readable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/127)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/toktok/toxcore/127#-KRQ4jLZQqwtfivPMRKB:-KRQ5Ps9lgW2LV3XRreZ:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/d038854bb9b82deaf82a95016fcd3577bdd11bf3/.travis.yml#L5)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> This is called $BUILD here, but $JOB in phase, one should be renamed.
</details>
Done.

---

*[other/travis/phase, line 13 at r1](https://reviewable.io:443/reviews/toktok/toxcore/127#-KRQ4a42jGptvx682AKb:-KRQ5Q_DWTvxYCs1VGN5:b-hssqik) ([raw file](https://github.com/toktok/toxcore/blob/d038854bb9b82deaf82a95016fcd3577bdd11bf3/other/travis/phase#L13)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Should we not use `${JOB}` here instead of  $1 to make it more readable?
</details>
That would be incorrect. `$1` is the first argument to `try_source` called below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/127)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/127#-:-KRQa6dR-4nMv7gT_j6r:b-jbsf8z)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/127#-:-KRQdPzsLke6iVVDPnVY:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/127)*

**Pull request closed without merging**
