### PR TITLE
Minor cleanups: header reordering, adding {}.

### PR DESCRIPTION
**Pull request by iphydf**
I hadn't done this for the "fun" code, yet. Also, we should include
system headers after our own headers.

"In general, a module should be implemented by one or more .cpp files.
Each of these .cpp files should include the header that defines their
interface first. This ensures that all of the dependences of the module
header have been properly added to the module header itself, and are not
implicit. System headers should be included after user headers for a
translation unit."
-- http://llvm.org/docs/CodingStandards.html#a-public-header-file-is-a-module

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/121)

### CODE REVIEW

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/121#-:-KREunUFDaRvqjQUf0nj:b-jbsf8z)*

**Comment by Encrypt** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/121#-:-KRFW0h3LWxFRBshp4X2:b-jbsf8z)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/121#-:-KRFwZuuXSkhTAI9yy-w:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/121#-:-KRFxolUWfdWb7YpdYpY:b-jbsf8z)*

**Pull request closed without merging**
