### PR TITLE
Group #include directives in 3-4 groups.

### PR DESCRIPTION
**Pull request by iphydf**
1. Current module (if C file).
2. Headers from current library.
3. Headers from other library (e.g. toxcore includes in toxav).
4. System headers.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/125)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxav/toxav_old.c, line 25 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQ7fJjzXELokq1qoSA:-KRQ7fJkba7sVCERjpkM:b-nzzn9m) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxav/toxav_old.c#L25)):*
> ```C
>  */
> 
> #include "toxav.h"
> ```

This section is audio support for groupchats. Is this a groupchat first module, adding audio support? Or is it an toxav module incorporating groupchat functions?

---

*[toxcore/assoc.c, line 7 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQ834rmEXwD8P3EuSn:-KRQ834rmEXwD8P3EuSo:bunos0f) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/assoc.c#L7)):*
> ```C
> #include "assoc.h"
> 
> #include "DHT.h"
> ```

Assoc is a superset of DHT, would DHT.c fit better in the current module group?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxav/toxav_old.c, line 25 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQ7fJjzXELokq1qoSA:-KRQ9lwILIDHlr43ad2t:b-hdnu16) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxav/toxav_old.c#L25)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> This section is audio support for groupchats. Is this a groupchat first module, adding audio support? Or is it an toxav module incorporating groupchat functions?
</details>
It should be toxav_group.c and toxav_group.h. I didn't change that in this PR to avoid unrelated changes. This PR is about include reordering.

---

*[toxcore/assoc.c, line 7 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQ834rmEXwD8P3EuSn:-KRQ9vp355EA9D0PJB1h:b-8lty5v) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/assoc.c#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Assoc is a superset of DHT, would DHT.c fit better in the current module group?
</details>
The rule is: $module.c includes $module.h as first thing. Everything else comes in blocks after it. Other than config.h, no exceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125#-:-KRQ_eejLz2KL7PTgOhe:b-jbsf8z)*

**Comment by nurupo** [comment]
Shouldn't this header inclusion policy be documented somewhere?

---

Reviewed 4 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125#-:-KRQgPvxtfxsKKXaL0K6:bf9fe41)*

**Comment by nurupo** [comment]
Reviewed 34 of 38 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/net_crypto.c, line 33 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQiBrqvUvJ0CI9N1hI:-KRQiBrqvUvJ0CI9N1hJ:b7ypmry) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/net_crypto.c#L33)):*
> ```C
> 
> #include "math.h"
> #include "util.h"
> ```

Shouldn't `util.h` be before `math.h`? Also it should be `<math.h>`

---

*[toxcore/tox.c, line 32 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQiyqKNA49xTGo8fft:-KRQiyqKNA49xTGo8ffu:b-s09ftn) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/tox.c#L32)):*
> ```C
> #include "tox.h"
> 
> #include "../toxencryptsave/defines.h"
> ```

That's a header from another library, should be moved 1 block down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125)*

**Comment by iphydf** [comment]
Yes, we should have all our policies documented. I'll do that in another PR at some point when I feel creative (or you can do it :).

---

Review status: 36 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/net_crypto.c, line 33 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQiBrqvUvJ0CI9N1hI:-KRT5aSzEIu-efEU7dN3:bkpo107) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/net_crypto.c#L33)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Shouldn't `util.h` be before `math.h`? Also it should be `<math.h>`
</details>
Yep. Didn't catch that one because it was "".

---

*[toxcore/tox.c, line 32 at r1](https://reviewable.io:443/reviews/toktok/toxcore/125#-KRQiyqKNA49xTGo8fft:-KRT5dqk1fQITZo1QmLv:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/472927dd5453d6898d5dade9aaf8a35c50013b48/toxcore/tox.c#L32)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> That's a header from another library, should be moved 1 block down.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125#-:-KRT5GV9BS0F38Mr3DR2:bszwewu)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/125#-:-KRVjElWiR5Z3eY6BcgD:b-jbsf8z)*

**Pull request closed without merging**
