### PR TITLE
Match parameter names in declarations with their definitions.

### PR DESCRIPTION
**Pull request by iphydf**
The parameter names were taken from function definitions to update the names in
function declarations (prototypes).

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/81)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

:shipit: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81#-:-KQZGuyRR4Dh3QIhusil:b-980vqi)*

**Comment by GrayHatter** [comment]
:lgtm_cancel: 

That's a lie tox.h.in and toxav.h.in

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81#-:-KQZH99orRKwGst-6afb:b-w11fui)*

**Comment by iphydf** [comment]
Done.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81#-:-KQZybmj42zjLkY9gKhG:b-896fix)*

**Comment by Diadlo** [comment]
Reviewed 3 of 5 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/tox.c, line 143 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/81#-KQ_gh7ywjqZHL3IxKBf:-KQ_gh7znlzSdkCoRraG:b8x0bxh) ([raw file](https://github.com/toktok/toxcore/blob/9e6e8af6f8666160024ccef9f9c6853ee68405e4/toxcore/tox.c#L143)):*
> ```C
> }
> 
> void tox_options_set_savedata_data(struct Tox_Options *options, const uint8_t *savedata_data, size_t savedata_length)
> ```

In `tox.h` we have `const uint8_t *data` as second parameter, and `size_t length` as last.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/tox.c, line 143 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/81#-KQ_gh7ywjqZHL3IxKBf:-KQ_iIX-3bYBiqXxuQey:b-2ps5pz) ([raw file](https://github.com/toktok/toxcore/blob/9e6e8af6f8666160024ccef9f9c6853ee68405e4/toxcore/tox.c#L143)):*
<details><summary><i>Previously, Diadlo (Diadlo) wrote…</i></summary>
> In `tox.h` we have `const uint8_t *data` as second parameter, and `size_t length` as last.
</details>
Do you sure, that `savedata_data` is correct name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81)*

**Comment by iphydf** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/tox.c, line 143 \[r2\]](https://reviewable.io:443/reviews/toktok/toxcore/81#-KQ_gh7ywjqZHL3IxKBf:-KQa0udp121x6vBzv1E3:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/9e6e8af6f8666160024ccef9f9c6853ee68405e4/toxcore/tox.c#L143)):*
<details><summary><i>Previously, Diadlo (Diadlo) wrote…</i></summary>
> Do you sure, that `savedata_data` is correct name?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81)*

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/81#-:-KQa17g1c-lKTBpqUUzi:bnfp4nl)*

**Pull request closed without merging**
