### PR TITLE
Use correct logical operator for tox_test

### PR DESCRIPTION
**Pull request by Chuongv**
Check to ensure that all 3 tox instances are up rather than
just one.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/123)

### CODE REVIEW

**Comment by iphydf** [comment]
:lgtm_strong:

It's not fixing an equality operator, though. It's fixing the logical operator in a truth test. Can you change "equality" to "logical" in the commit message?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/123#-:-KRNdFy3r4Krg137I8iL:bnr2t9)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/123#-:-KRPV90hVMLWPvEP3-3N:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/123#-:-KRQIcTsyyWgozwgBNas:b-jbsf8z)*

**Comment by iphydf** [comment]
I see you've changed it. Would have been nice if you had notified me of the update.

**Pull request merged**
