### PR TITLE
Improve static and const correctness.

### PR DESCRIPTION
**Pull request by iphydf**
- Any non-externally-visible declarations should be `static`.
- Casting away the `const` qualifier from pointers-to-const is
  dangerous. All but one instance of this are now correct. The one
  instance where we can't keep `const` is one where toxav code actually
  writes to a chunk of memory marked as `const`. This code also assumes
  4 byte alignment of data packets. I don't know whether that is a valid
  assumption, but it's likely unportable, and *not* obviously correct.
- Replaced empty parameter lists with `(void)` to avoid passing
  parameters to it. Empty parameter lists are old style declarations for
  unknown number and type of arguments.
- Commented out (as `#if DHT_HARDENING` block) the hardening code that
  was never executed.
- Minor style fix: don't use `default` in enum-switches unless the number
  of enumerators in the default case is very large. In this case, it was
  2, so we want to list them both explicitly to be warned about missing
  one if we add one in the future.
- Removed the only two function declarations from nTox.h and put them
  into nTox.c. They are not used outside and nTox is not a library.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/97)

### CODE REVIEW

**Comment by nurupo** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxav/msi.c, line 685 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQxAfrSpDNFh-mwrLKz:-KQxAfrSpDNFh-mwrLL-:bkgfhvj) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxav/msi.c#L685)):*
> ```C
>         break;
> 
>         case msi_CallRequested:
> ```

`// intentional fall-through`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97)*

**Comment by GrayHatter** [comment]
Reviewed 36 of 38 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[testing/DHT_test.c, line 157 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQyueXGULFabAy-WqHF:-KQyueXHtRTYy1u_lfWh:b-p9zzwh) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/testing/DHT_test.c#L157)):*
> ```C
> 
> #if 0
> static void printpacket(uint8_t *data, uint32_t length, IP_Port ip_port)
> ```

wouldn't this be better in an `#if NDEBUG` block?

---

*[toxav/msi.c, line 685 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQxAfrSpDNFh-mwrLKz:-KQyvJlry_sFsGqldp3m:b-kr4hkf) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxav/msi.c#L685)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> `// intentional fall-through`
</details>
Usually the lack of curly braces means it's an intentional fall through.

Either way is fine with me.

---

*[toxcore/Messenger.c, line 59 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQyvkHuhEse_zqwT62B:-KQyvkHvOkhebAfJXItV:b-u8h9zv) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxcore/Messenger.c#L59)):*
> ```C
>  *  return -1 if realloc fails.
>  */
> static int realloc_friendlist(Messenger *m, uint32_t num)
> ```

FYI this change will be reverted in multidevice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97)*

**Comment by iphydf** [comment]
Review status: 19 of 38 files reviewed at latest revision, 3 unresolved discussions.

---

*[testing/DHT_test.c, line 157 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQyueXGULFabAy-WqHF:-KQz4_zrmqowhbYZ_DAe:b-uo6om0) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/testing/DHT_test.c#L157)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> wouldn't this be better in an `#if NDEBUG` block?
</details>
It's used in the "slvrTODO" block at the bottom. NDEBUG is inappropriate. I've added an slvrTODO here as well.

---

*[toxav/msi.c, line 685 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQxAfrSpDNFh-mwrLKz:-KQz5MTsBdR841s9p-ug:b-5mmnzk) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxav/msi.c#L685)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Usually the lack of curly braces means it's an intentional fall through.
> 
> Either way is fine with me.
</details>
In other parts of the code, this is not standard practice. You're welcome to go through all `switch` statements and add comments like that in a separate PR, but in this PR, I'd like to be consistent with the surrounding code.

---

*[toxcore/Messenger.c, line 59 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQyvkHuhEse_zqwT62B:-KQz6FOO7F7TqpgUy3gr:b-54snbz) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxcore/Messenger.c#L59)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> FYI this change will be reverted in multidevice
</details>
Acknowledged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97#-:-KR1N3_5eGyj1AaTbi90:b-jbsf8z)*

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Reviewed 19 of 38 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97#-:-KR1fHhA5Qc_Cq6gbZYH:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxav/msi.c, line 685 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQxAfrSpDNFh-mwrLKz:-KR2HGDrQyM8erMOqH43:b-4fss7) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxav/msi.c#L685)):*
It is a standard practice in `tox-boostrapd`!

Oh well, too bad it's all or nothing.

>Usually the lack of curly braces means it's an intentional fall through.

Use of curly braces is entirely optional though, they are not required for multi-line case. Unless irungentoo always uses them like that, the "no curely braces" = "fall through" is a rather questionable oracle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97#-:-KR2JGZx3VIHmFpX_NN-:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxav/msi.c, line 685 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/97#-KQxAfrSpDNFh-mwrLKz:-KR2o4cayTYkPf0tPquG:but0y8s) ([raw file](https://github.com/toktok/toxcore/blob/7eb80c0d2d86e2c492d818662fa99e90cf7e563e/toxav/msi.c#L685)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> It is a standard practice in `tox-boostrapd`!
> 
> Oh well, too bad it's all or nothing.
> 
> >Usually the lack of curly braces means it's an intentional fall through.
> 
> Use of curly braces is entirely optional though, they are not required for multi-line case. Unless irungentoo always uses them like that, the "no curely braces" = "fall through" is a rather questionable oracle.
</details>
I see. I think an uninterrupted sequence of case statements doesn't need fall-through comments. It's very obvious that it's a fall-through. If there is any statement between two case statements, it definitely requires such a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/97)*

**Pull request closed without merging**
