### PR TITLE
Make group callbacks stateless

### PR DESCRIPTION
**Pull request by JFreegman**
---
This change is NOT reviewable. Use Github reviews instead.

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/Messenger.c, line 821 at r1](https://reviewable.io:443/reviews/toktok/toxcore/146#-KRycn9INFQdynipgFcM:-KRycn9JTFfqLn-itsv5:bvm4bgy) ([raw file](https://github.com/toktok/toxcore/blob/5db5d9c0a2f5d1afc79ef791c4c8febacfd6a5da/toxcore/Messenger.c#L821)):*
> ```C
> 
>     m->friendlist[friendnumber].statusmessage_length = length;
>     return 0;group_invite)(m, i
> ```

huh, what's that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by JFreegman** [comment]
*[toxcore/Messenger.c, line 821 at r1](https://reviewable.io:443/reviews/toktok/toxcore/146#-KRycn9INFQdynipgFcM:-KRyhIzuGj5qsch04Xx7:bczcomm) ([raw file](https://github.com/toktok/toxcore/blob/5db5d9c0a2f5d1afc79ef791c4c8febacfd6a5da/toxcore/Messenger.c#L821)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> huh, what's that?
</details>
Think I must've accidentally ctrl+v'd before I pushed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by GrayHatter** [comment]
Reviewed 7 of 10 files at r1, 2 of 2 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[toxcore/group.c, line 455 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BYZ24M16WHqNdu2M:-KS-BYZ24M16WHqNdu2N:b-wmvmk3) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L455)):*
> ```C
>     add_to_closest(g_c, groupnumber, real_pk, temp_pk);
> 
>     if (do_gc_callback && g_c->group_namelistchange) {
> ```

Do we want a comment here explaining that this isn't the desired behavior?

---

*[toxcore/group.c, line 459 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BOIS0YwjLkjdfWs7:-KS-BOIS0YwjLkjdfWs8:bq8vjgg) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L459)):*
> ```C
>     }
> 
>     if (g->peer_on_join) {
> ```

does this need to check `do_gc_callback`?

---

*[toxcore/Messenger.h, line 257 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-CRo9xvRz3-T34tGm:-KS-CRo9xvRz3-T34tGn:bogi4wv) ([raw file](https://github.com/toktok/toxcore/blob/f41b010e9b9459295bd8e030159a27db463cde33/toxcore/Messenger.h#L257)):*
> ```objc
>     void *group_chat_object; /* Set by new_groupchats()*/
>     void (*group_invite)(struct Messenger *m, uint32_t, const uint8_t *, uint16_t);
>     void (*group_message)(struct Messenger *m, uint32_t, const uint8_t *, uint16_t);
> ```

Where was this moved? Or why was it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by JFreegman** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[toxcore/group.c, line 455 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BYZ24M16WHqNdu2M:-KS-DOTvc0AYpJW0Skf2:bxfh11v) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L455)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Do we want a comment here explaining that this isn't the desired behavior?
</details>
I'm not sure what you mean. This behaviour is desired - we want to control when the callback is triggered.

---

*[toxcore/group.c, line 459 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BOIS0YwjLkjdfWs7:-KS-DaG--wjcc1nQvihp:b-t2yhnt) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L459)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> does this need to check `do_gc_callback`?
</details>
That callback doesn't take a userdata object so it should be safe. It and the other two callbacks inside the Group_C struct are set by ToxAV, rather than by the public API. I'm not sure what disabling them would do, but it's something we might want to look into outside of this PR.

---

*[toxcore/Messenger.h, line 257 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-CRo9xvRz3-T34tGm:-KS-EBkgbgZrv7WuQf3V:b-2jtaoa) ([raw file](https://github.com/toktok/toxcore/blob/f41b010e9b9459295bd8e030159a27db463cde33/toxcore/Messenger.h#L257)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Where was this moved? Or why was it here?
</details>
That was always there. It's needed in Messenger because there's no group yet when you receive an invite packet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by JFreegman** [comment]
*[toxcore/Messenger.h, line 257 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-CRo9xvRz3-T34tGm:-KS-MgE7hc5s94RTpode:b-92xzl1) ([raw file](https://github.com/toktok/toxcore/blob/f41b010e9b9459295bd8e030159a27db463cde33/toxcore/Messenger.h#L257)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> That was always there. It's needed in Messenger because there's no group yet when you receive an invite packet.
</details>
Oh you meant group_message, for some reason reviewable hid that line from your quote. I have no idea what it was for, but it wasn't being used and seemed out of place so I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[toxcore/group.c, line 455 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BYZ24M16WHqNdu2M:-KS0Jwlxsa9cj9-B3g6E:b-ufkenh) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L455)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> I'm not sure what you mean. This behaviour is desired - we want to control when the callback is triggered.
</details>
no I mean the desired behavior is not having to make this check because tox_iterate() is supposed to be the only function sending callbacks. 

---

*[toxcore/Messenger.h, line 257 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-CRo9xvRz3-T34tGm:-KS0KEOAmyBOJJKyf_ZE:b4tcq2i) ([raw file](https://github.com/toktok/toxcore/blob/f41b010e9b9459295bd8e030159a27db463cde33/toxcore/Messenger.h#L257)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> Oh you meant group_message, for some reason reviewable hid that line from your quote. I have no idea what it was for, but it wasn't being used and seemed out of place so I removed it.
</details>
LGTM

That's what I figured, just wanted to make sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146#-:-KS0KKmUMPgH_uIzRZ88:bg7igkv)*

**Comment by JFreegman** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[toxcore/group.c, line 455 at r2](https://reviewable.io:443/reviews/toktok/toxcore/146#-KS-BYZ24M16WHqNdu2M:-KS2EG7s6ymvwkH944O_:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/d05545dc2b12ff2919f916fd424375eac1d85f85/toxcore/group.c#L455)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> no I mean the desired behavior is not having to make this check because tox_iterate() is supposed to be the only function sending callbacks. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146#-:-KS2NM_jRrxH-tBWzFAJ:bg7igkv)*

**Comment by nurupo** [comment]
Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/146#-:-KS2n__d-Lhc1t0Asswc:b-jbsf8z)*

**Pull request merged**
