### PR TITLE
 Replace *Tox as a pointer to *Messenger to it's own struct

### PR DESCRIPTION
**Pull request by GrayHatter**
Oh, boy... I knew this commit was going to be huge, but I didn't know how big.
There's no way to make this smaller, without breaking more stuff, as it is, it
only compiles if you
./configure --disable-tests --disable-testing --disable-av ...

For the most of it, It's a lot of sane renames, and close consideration. With
the notable exception of group.{c,h} & tox_old_code.h. Both of which I decided
to do bulk replacements of *Group_Chats to *Tox, and linking the code on line 1
of the function to avoid changing a lot of lines with important code. I decided
to do it this way because the global plan for toxcore is to replace the current
groupchats with something better. So this change was quick, instead of detailed.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/19)

### CODE REVIEW

**Comment by GrayHatter** [comment]
The first 2 commits will be dropped after #18 is merged. That should make this commit easier to read.

**Comment by GrayHatter** [comment]
I assigned a little bit of everyone. @JFreegman and @nurupo because the last I heard, you want to make sure someone reviews the changes I make to toxcore. Here's your chance. @irungentoo PTAL, I'm sure there's something I could be doing better if I knew as much about toxcore as you. 

@tux3 you're really the one I think will be able to give it the most time/attention. It's a little messy around the save new save functions you wrote (removed). They're coming next.

@Encrypt @endoffile78 Same as #18, the more toxcore code you see the more you'll be able to help. (And another pair of eyes never hurt!)

Thanks guys!

**Comment by nurupo** [comment]
Hm, can't open Reviewable for this. Does it require builds to pass first?

**Comment by nurupo** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[toxcore/tox.h, line 40 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOcAXSFbwpXeXEURX0H:-KOcAXSFbwpXeXEURX0I:b8eoml5) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L40)):*
> ```objc
>  * `tox.in.h`, located in `other/apidsl/`. For instructions on how to        *
>  * generate `tox.h` from `tox.in.h` please refer to `other/apidsl/README.md` *
>  ******************************************************************************/
> ```

*cough* *cough*

This will also cause Travis to fail.

---

*[toxcore/tox.h, line 586 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOc9n4VSFr2sEqYHv1z:-KOc9n4VSFr2sEqYHv2-:bdajqcj) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L586)):*
> ```objc
>     uint64_t        uptime;
> };
> ```

Why is Tox struct defined in the public API, in the tox.h, instead of being an opaque pointer for public API and being defined in the internal API? Users of the public API can't do anything with the members of the Tox struct, so there is no point in showing them what is inside of it. Also, if we add a new member to the Tox struct, that will break the ABI compatibility, which wouldn't be the case if you kept it as an opaque pointer, like it was before your change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/19)*

**Comment by nurupo** [comment]
That was just me quickly glancing over it, will look into it closer at a later time.

@GrayHatter also, what is the reason of this change, why it was made?

**Comment by nurupo** [comment]
Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[toxcore/tox.h, line 153 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOcCC7-1r8mtBuv949L:-KOcCC7-1r8mtBuv949M:b-yah6u7) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L153)):*
> ```objc
>  * incremented.
>  */
> #define TOX_VERSION_MINOR               1u
> ```

Don't think it's a good idea to increment version in a feature PR. For example, consider having 3 PRs open, two with major change and one with minor. If we merge them, we will change the version like so 0.0.0 -> 1.0.0 -> 1.0.0 -> 0.0.1. It makes more sense to not touch version numbers in feature PRs and have separate version release PRs, which update versions only, right before releasing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/19)*

**Comment by GrayHatter** [comment]
The origin of this change is to rip messenger out of toxcore, or rip toxcore out of messenger (depending on your frame of reference. 

Right now (as you noted below), *Tox is just a reference to  *Messenger. All of the "core" logic right now is done through messenger. That requires Messenger to exist for any other section to be active/working. It also means you can't interact with anything on a lower level without also changing Messenger. Considering the other levels of abstraction/separation throughout toxcore, this doesn't' make much sense. It also limits what you can do with toxcore in the future. There's no reason to run a whole Messenger, if you're just running a bootstrap node. (Which IMO  currently exists as hack, and not really as it should be). You also can't disable the DHT without doing something stupid to Messenger. This would be a huge benefit to mobile users, to be able to turn on and off the DHT while still maintaining their active session and connections to existing contacts. Also group chats, there's no reason to start a Messenger instance and join the DHT if you're only interested in a single group chat. Doing it this way also allows other pending features, like Multi-Device, ToxVPN, ToxFileServer, ToxAsAService, all to exist seperate from, or in addition to Messenger, without interfering.  

I have a few more ideas/plans for Toxcore that would be a lot simpler to implement and advantageous as a feature with this change. 

---

Review status: 0 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[toxcore/tox.h, line 40 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOcAXSFbwpXeXEURX0H:-KOcISuShTmyN4vlNkdE:b-l4r14j) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L40)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> *cough* *cough*
> 
> This will also cause Travis to fail.
</details>
I'll fix this once this PR is a little closer to final.

---

*[toxcore/tox.h, line 153 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOcCC7-1r8mtBuv949L:-KOcIZqP4_sogyp26iF7:b12xcyr) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L153)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Don't think it's a good idea to increment version in a feature PR. For example, consider having 3 PRs open, two with major change and one with minor. If we merge them, we will change the version like so 0.0.0 -> 1.0.0 -> 1.0.0 -> 0.0.1. It makes more sense to not touch version numbers in feature PRs and have separate version release PRs, which update versions only, right before releasing it.
</details>
Agreed, I'll change this is my next commit. ( This came over when I changed it so I could compile uTox with or without multi device depending on what version of toxcore is installed.)

We'll also need a development/staging branch soon too then.

---

*[toxcore/tox.h, line 586 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/19#-KOc9n4VSFr2sEqYHv1z:-KOcJ5NjJS5_JSGUN_0a:b-n19rk6) ([raw file](https://github.com/toktok/toxcore/blob/d9c103f4ddf7e0427b7eef68810594be7389e8e9/toxcore/tox.h#L586)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Why is Tox struct defined in the public API, in the tox.h, instead of being an opaque pointer for public API and being defined in the internal API? Users of the public API can't do anything with the members of the Tox struct, so there is no point in showing them what is inside of it. Also, if we add a new member to the Tox struct, that will break the ABI compatibility, which wouldn't be the case if you kept it as an opaque pointer, like it was before your change.
</details>
Are you advocating we add an additional layer of abstraction to the Tox struct? Or that this change in general is a bad idea?

If you know the code in the backend, there's no reason you can't interact with the members of the Tox struct, be it an extra pointer to the Messenger struct , you typecast. Or as a or you can continue to use the API as it is now. Either way I'm not sure why an ABI change (without a corresponding forced API change) is significant in this case. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/19#-:-KOcFD-MUtQCv38udJVL:b3ib9fm)*

**Comment by iphydf** [comment]
Assign me when this PR compiles and is based on master.

**Comment by GrayHatter** [comment]
For anyone not following the IRC conversations: The consensus seems to be that exposing the Tox struct to the api is a bad idea. But better solution is still under discussion.

**Comment by iphydf** [comment]
We'll hold off on this for a bit and discuss. Until then I'm closing this PR to avoid clutter.

**Pull request closed without merging**
