### PR TITLE
3. Travis astyle

### PR DESCRIPTION
**Pull request by iphydf**
Depends on #16

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/20)

### CODE REVIEW

**Comment by nurupo** [comment]
Define "depends". Is it based on #16's branch, instead of master?

**Comment by nurupo** [comment]
I see, I guess you meant "replaces".

**Comment by iphydf** [comment]
I meant depends as in "is based on", but then I decided to drop the old one instead.

**Comment by nurupo** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[other/travis/toxcore-script, line 9 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/20#-KOmsHGW3t56aUqnGmNc:-KOmsHGW3t56aUqnGmNd:b-itofr2) ([raw file](https://github.com/toktok/toxcore/blob/9247d8221b3b770eb74693342a2dc5b821606565/other/travis/toxcore-script#L9)):*
> ```
> ../apidsl/_build/apigen.native other/apidsl/toxav.in.h | $ASTYLE --options=other/astyle/astylerc > toxav/toxav.h
> # Check if the code is formatted according to the astyle configuration.
> $ASTYLE --options=other/astyle/astylerc tox*/*.[ch]
> ```

Just `tox*/*.[ch]`? There are, at very least,  also `other/*.[ch]` and `other/bootstrap_daemon/src/*.[ch]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20)*

**Comment by nurupo** [comment]
Although it's out of scope of this PR, I just want to remind that there was a discussion about changing [tox*_version_is_compatible()](https://github.com/irungentoo/toxcore/pull/1527) functions to use a macro, which might be an idea for a next PR someone makes.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20#-:-KOmtC3R54q2QSCeqPTZ:b-o69ekw)*

**Comment by iphydf** [comment]
Review status: 9 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[other/travis/toxcore-script, line 9 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/20#-KOmsHGW3t56aUqnGmNc:-KOnlFaBjj_XDjUdhoiV:b-mj70vl) ([raw file](https://github.com/toktok/toxcore/blob/9247d8221b3b770eb74693342a2dc5b821606565/other/travis/toxcore-script#L9)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Just `tox*/*.[ch]`? There are, at very least,  also `other/*.[ch]` and `other/bootstrap_daemon/src/*.[ch]`.
</details>
I wanted to avoid a complex expression, but I've changed my mind. It's better we format everything we can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20)*

**Comment by iphydf** [comment]
It is indeed out of scope. This comment will get lost. You could instead open a ticket to keep track of the discussion.

---

Review status: 9 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20#-:-KOnlRPlSryh3u_J1dfk:b-lsd1jv)*

**Comment by iphydf** [comment]
@nurupo is this one good to go now?

**Comment by GrayHatter** [comment]
LGTM

---

Reviewed 7 of 10 files at r1, 5 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20#-:-KOw1o9j__NwehPCVZb9:bb6ywmx)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20#-:-KOw20ucXEoUf7oLZj5C:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/20#-:-KOw2Jc7TOwoEk4JIsyk:bnfp4nl)*

**Pull request merged**
