### PR TITLE
Add missing DHT_bootstrap to CMakeLists.txt.

### PR DESCRIPTION
**Pull request by iphydf**
- This PR also adds a DEBUG cmake option that enables -DDEBUG.
- We also remove `-Wall`, because there are too many warnings, and nobody really
  looks at them at the moment. We'll see about fixing them soon. We'll also want
  to enable `-Werror` at some point.
- We also factor out `nproc` calls into the env scripts so we can use `sysctl` on OSX where `nproc` doesn't exist.
- Finally, this PR enables `-O3` to make sure toxcore still works correctly
  under heavy compiler optimisations.

--
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/37)

### CODE REVIEW

**Comment by nurupo** [comment]
Given that `tox-bootstrapd` has got `--foreground` option, we might consider deprecating `DHT_bootstrap`.`tox-bootstrapd` should have same features `DHT_bootstrap` has and even more, at the down side of using a config file instead of command line arguments.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/37#-KPPFFL1XHS9mz9c4tzo:-KPPFFL1XHS9mz9c4tzp:b-p0pstg) ([raw file](https://github.com/toktok/toxcore/blob/1bde019d5e376979e34a063811f3ec67278200fe/CMakeLists.txt#L28)):*
> ```CMake
> option(DEBUG "Enable assertions and other debugging facilities" OFF)
> if(DEBUG)
>   add_definitions(-DDEBUG=1)
> ```

`DEBUG` is rather a common word. Are we sure that nothing is using it besides Tox libraries? e.g. no third party header files Tox libraries include use `DEBUG` and no compiler sets `DEBUG` for debug builds automatically? If we are not sure, `TOX_DEBUG` might be a safer bet. `TOX_DEBUG` would also match the naming of `TOX_LOGGER`. (No idea why `LOGGER_LEVEL` and `LOGGER_OUTPUT_FILE` are not prefixed with `TOX_` though...)

---

*[CMakeLists.txt, line 120 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/37#-KPPG7HfVkGO-RLXMvrr:-KPPG7Hg2LZfxd8iqGcg:bp921yy) ([raw file](https://github.com/toktok/toxcore/blob/1bde019d5e376979e34a063811f3ec67278200fe/CMakeLists.txt#L120)):*
> ```CMake
>   target_link_libraries(toxnetwork ${RT_LIBRARIES})
>   set(toxcore_PKGCONFIG_LIBS ${toxcore_PKGCONFIG_LIBS} "-lrt")
> endif()
> ```

Since this block adds linking libraries to `toxnetwork`, why not put this block right under the `add_library(toxnetwork ${LIBTYPE}`, instead of having it under `toxdht`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPPEidzDvU9WV5KxlHe:b-k8bep6)*

**Comment by nurupo** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37)*

**Comment by iphydf** [comment]
I'd like to do that in a separate PR. If you like, you can make a PR to do it.

---

Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/37#-KPPFFL1XHS9mz9c4tzo:-KPPLCYEWozaQ_J9uUj3:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/1bde019d5e376979e34a063811f3ec67278200fe/CMakeLists.txt#L28)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> `DEBUG` is rather a common word. Are we sure that nothing is using it besides Tox libraries? e.g. no third party header files Tox libraries include use `DEBUG` and no compiler sets `DEBUG` for debug builds automatically? If we are not sure, `TOX_DEBUG` might be a safer bet. `TOX_DEBUG` would also match the naming of `TOX_LOGGER`. (No idea why `LOGGER_LEVEL` and `LOGGER_OUTPUT_FILE` are not prefixed with `TOX_` though...)
</details>
Done.

---

*[CMakeLists.txt, line 120 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/37#-KPPG7HfVkGO-RLXMvrr:-KPPLLukWFh25qTdtjlj:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/1bde019d5e376979e34a063811f3ec67278200fe/CMakeLists.txt#L120)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> Since this block adds linking libraries to `toxnetwork`, why not put this block right under the `add_library(toxnetwork ${LIBTYPE}`, instead of having it under `toxdht`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPPJt_bScRJ7d1fntbn:b1mjeyk)*

**Comment by nurupo** [comment]
I was looking for a change in `configure.ac` that would do `s/DEBUG/TOX_DEBUG/`, but apparently we never had an option for enabling DEBUG in autotools build system? Did I miss it or it's really not there?

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPPYzj-NqBke_y9YORY:bf3lsj1)*

**Comment by iphydf** [comment]
It doesn't exist. I looked for it as well.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPP_jVa_I7FHvMr3N5r:b-7g5fr4)*

**Comment by nurupo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPPb_ilD1bBxGPkiqCV:bnfp4nl)*

**Comment by GrayHatter** [comment]
:lgtm:

!! See comments in #36 near, but unrelated to changes made here !!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/37#-:-KPPgsc5Q-LoqDJB1w0J:b-vfmk9z)*

**Pull request merged**
