### PR TITLE
Sort #includes in all source files.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/80)

### CODE REVIEW

**Comment by nurupo** [comment]
Review status: 0 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/network.h, line 29 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/80#-KQYHtt33wpTT2CLXceu:-KQYHtt33wpTT2CLXcev:btpzcdq) ([raw file](https://github.com/toktok/toxcore/blob/3a9300368d31b0460bd70effd14451303493b109/toxcore/network.h#L29)):*
> ```objc
> #ifdef PLAN9
> #include <u.h> //Plan 9 requires this is imported first
> #include <libc.h>
> ```

In some cases order of imports matters. Apparently this is one of them.

From my experience, Windows also has this issue with some headers. Not sure if toxcore uses such Windows headers though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80)*

**Comment by nurupo** [comment]
Review status: 0 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/network.h, line 29 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/80#-KQYHtt33wpTT2CLXceu:-KQYIEjizhshHopaKRY8:b-ims5su) ([raw file](https://github.com/toktok/toxcore/blob/3a9300368d31b0460bd70effd14451303493b109/toxcore/network.h#L29)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> In some cases order of imports matters. Apparently this is one of them.
> 
> From my experience, Windows also has this issue with some headers. Not sure if toxcore uses such Windows headers though.
</details>
s/imports/includes/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80)*

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80#-:-KQYJchrETKR6N_9apCW:bnfp4nl)*

**Comment by GrayHatter** [comment]
Reviewed 53 of 54 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/network.h, line 29 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/80#-KQYHtt33wpTT2CLXceu:-KQZJIb88IDDV5AeRPX_:b-3e2mu6) ([raw file](https://github.com/toktok/toxcore/blob/3a9300368d31b0460bd70effd14451303493b109/toxcore/network.h#L29)):*
<details><summary><i>Previously, nurupo wrote…</i></summary>
> s/imports/includes/
</details>
I'll echo windows being very particular about the order of includes. In this case, my guess is @iphydf is slowing moving toxcore to working within .clang-format. If that's the case, we have a few options. We could `// clang-format off` followed by `// clang-format on` Or break this into two duplicate #if blocks. Either would require comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80)*

**Comment by iphydf** [comment]
Review status: 53 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/network.h, line 29 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/80#-KQYHtt33wpTT2CLXceu:-KQZnGNf78opp4IiYNFf:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/3a9300368d31b0460bd70effd14451303493b109/toxcore/network.h#L29)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> I'll echo windows being very particular about the order of includes. In this case, my guess is @iphydf is slowing moving toxcore to working within .clang-format. If that's the case, we have a few options. We could `// clang-format off` followed by `// clang-format on` Or break this into two duplicate #if blocks. Either would require comments.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80)*

**Comment by JFreegman** [comment]
:lgtm:

---

Reviewed 49 of 54 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/80#-:-KQan3GyGvgMrMg2tS0r:bnfp4nl)*

**Pull request closed without merging**
