### PR TITLE
Bulk rename friend_connection -> tox_connection

### PR DESCRIPTION
**Pull request by GrayHatter**
This commit is part of Multi-Device, and is needed to make toxcore more modular.

@iphydf Not sure you can review this yet, but I want you to be aware of it's existence.

@tux3 PTAL should be an easy sign off.

@endoffile78 @Encrypt I'm still assuming you want to help with toxcore more? This is a good PR to start with, It'll give you a good intro to some of toxcore.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/18)

### CODE REVIEW

**Comment by endoffile78** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by endoffile78** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18#-:-KObIHE65fO1-Tf7pjwP:bnfp4nl)*

**Comment by sudden6** [comment]
*[toxcore/tox_connection.h, line 121 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOfeTK44AZKfEuCLI6H:-KOfeTK5qxuKcyYkOD7b:b-ls0p34) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L121)):*
> ```objc
>  * return -1 on failure.
>  */
> int gettox_conn_id_pk(Tox_Connections *tox_conns, const uint8_t *real_pk);
> ```

any reason not to name this `get_tox_conn_id_pk`? would fit to the rest better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by sudden6** [comment]
*[toxcore/tox_connection.h, line 152 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOff2gER8v1uP8QeXLJ:-KOff2gER8v1uP8QeXLK:b-w8lchs) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L152)):*
> ```objc
>  * return 0 on success.
>  */
> int toxconn_add_tcp_relay(Tox_Connections *tox_conns, int toxconn_id, IP_Port ip_port, const uint8_t *public_key);
> ```

`tox_conn_add_tcp_relay` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by sudden6** [comment]
*[toxcore/tox_connection.h, line 202 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOffL6KVtarQuOeZIbZ:-KOffL6LZyZB5iwtdgx8:bxywnhw) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L202)):*
> ```objc
>  */
> void set_tox_conn_request_callback(Tox_Connections *tox_conns,
>                                    int (*toxconn_request_callback)(void *, const uint8_t *,const uint8_t *, uint16_t),
> ```

`tox_conn_request_callback` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[toxcore/tox_connection.h, line 113 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOffWqwuunF9kd-1yJg:-KOffWqwuunF9kd-1yJh:b-qh9xae) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L113)):*
> ```objc
> 
>     int (*toxconn_request_callback)(void *object, const uint8_t *source_pubkey, const uint8_t *data, uint16_t len);
>     void *toxconn_request_object;
> ```

`tox_conn_request_object` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[toxcore/tox_connection.h, line 113 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOffWqwuunF9kd-1yJg:-KOfg9h_xoSHKifSJCgC:bb73xfv) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L113)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> `tox_conn_request_object` ?
</details>
Same

---

*[toxcore/tox_connection.h, line 121 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOfeTK44AZKfEuCLI6H:-KOffQBnL9LnIu8YTCXx:bebz5do) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L121)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> any reason not to name this `get_tox_conn_id_pk`? would fit to the rest better.
</details>
This is fixed in my next PR, I decided half way through the refactor to stick to the toxconn naming patern. 

---

*[toxcore/tox_connection.h, line 152 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOff2gER8v1uP8QeXLJ:-KOffjzJ5JaL5wEIGAQM:bpsonws) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L152)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> `tox_conn_add_tcp_relay` ?
</details>
No, per jfreegman's suggestion, i'm strictly avoiding the ^tox_ function naming to avoid clobbering the API namespace

---

*[toxcore/tox_connection.h, line 202 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KOffL6KVtarQuOeZIbZ:-KOfg39pRpyFdeUJ2w0G:b-34vmyd) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/tox_connection.h#L202)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> `tox_conn_request_callback` ?
</details>
See above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Comment by sudden6** [comment]
the renaming could use a little more consistency, I'd suggest `tox_conn` everywhere instead of `tox_connection` and ` `tox_conn` mixed.

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[toxcore/friend_requests.c, line 143 \[r1\]](https://reviewable.io:443/reviews/toktok/toxcore/18#-KPGOiFmS7l43Bo6CGj1:-KPGOiFmS7l43Bo6CGj2:bh03lon) ([raw file](https://github.com/toktok/toxcore/blob/350b2f8820629ac77a36fef967be0ad1d1a4e73f/toxcore/friend_requests.c#L143)):*
> ```C
> void friendreq_init(Friend_Requests *fr, Tox_Connections *fr_c)
> {
>     set_tox_conn_request_callback(fr_c, &friendreq_handlepacket, fr);
> ```

I understand what Friend Request is, it's when someone requests us to be their friend, but what Tox Connection Request is supposed to mean? I think it has a very different meaning. Tox Connection Request would mean that someone wants to connect to us, which should happen every single time we connect to someone, which is completely different from friend requests. Shouldn't that be `tox_conn_friend_request_callback`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/18)*

**Pull request closed without merging**
