### PR TITLE
added assert to crypto_core.c@encrypt_data_symmetric

### PR DESCRIPTION
**Pull request by GrayHatter**
pulled from #5 @piling

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/6)

### CODE REVIEW

**Comment by GrayHatter** [comment]
@piling @chuongv

**Comment by JFreegman** [comment]
This makes no sense. Asserts are for debug builds, not production. That length check always needs to be made.

**Comment by GrayHatter** [comment]
@JFreegman the check is made by every single one of the callers

 @iphydf

**Comment by JFreegman** [comment]
@GrayHatter No it's not, but it shouldn't matter either way. Either the function needs to check if the value is zero, or it doesn't. Removing a boundary check but adding an assert is schizophrenic.

**Comment by JFreegman** [comment]
I highly recommend reading this: http://blog.regehr.org/archives/1091

**Comment by GrayHatter** [comment]
> @GrayHatter No it's not,

@JFreegman what fxn calls encrypt_data_symmetric() without first checking the length?

**Comment by JFreegman** [comment]
@grayhatter https://github.com/GrayHatter/toxcore/blob/4a7e631f15a2c114090cece24de7e460363e8d8e/toxcore/crypto_core.c#L126

**Comment by piling** [comment]
@GrayHatter but every fxn calls encrypt_data() checks for the length.
@JFreegman 
Not fan of assertations but if we use them properly as @iphydf said [here](https://github.com/TokTok/toxcore/issues/8#issuecomment-231561869) i dont see any problem.

**Pull request closed without merging**
