### PR TITLE
Make Message received receipts stateless

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/58)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/58#-:-KPenk6UaD57tiAxqknG:bnfp4nl)*

**Comment by iphydf** [comment]
:lgtm: what a shitty tool reviewable is :\ and it's still the best.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/58#-:-KPlk5dqdkNd918C4npT:bb4kygw)*

**Comment by iphydf** [comment]
Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/58)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/58)*

**Pull request merged**
