### PR TITLE
Ensure that all TODOs have an owner.

### PR DESCRIPTION
**Pull request by iphydf**
In the future, all TODOs added either need a bug number (TODO(#NN)) or a
person's github user name. By default, I made irungentoo the owner of
all toxcore TODOs, mannol the owner of toxav TODOs, and myself the owner
of API TODOs.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/133)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 26 of 26 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/133#-:-KRVoefGsNH4tZ1wTtn1:b-jbsf8z)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/133#-:-KRVynxJz0DJNf5MJ6i-:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Reviewed 6 of 16 files at r4.
Review status: 22 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 2442 at r4](https://reviewable.io:443/reviews/toktok/toxcore/133#-KRlRJrRqQkOTeSuz5-W:-KRlRJrRqQkOTeSuz5-X:bpxtq2f) ([raw file](https://github.com/toktok/toxcore/blob/b225cb8242af83558a6bbcd1e857644147757d41/toxcore/Messenger.c#L2442)):*
> ```C
> 
> /* Minimum messenger run interval in ms
>    TODO(irungentoo): A/V */
> ```

this should either be removed, or assigned to @mannol

The argument for removing: toxav doesn't need additional or less time, even if we do need to reduce this number for toxav (unlikely IMO) then it should be renamed to messenger min and we should ignore it when toxav is active.

finally; this should be dropped completely. Messenger isn't smarter than crypto_run_interval. and if it is, we should fix that, no this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/133)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 10 of 16 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/133#-:-KRlSehtaLK6AVbZuRfS:b-jbsf8z)*

**Comment by iphydf** [comment]
Review status: 31 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 2442 at r4](https://reviewable.io:443/reviews/toktok/toxcore/133#-KRlRJrRqQkOTeSuz5-W:-KRmTqY3fGVeQ-VXY2Xt:bf1z9ux) ([raw file](https://github.com/toktok/toxcore/blob/c8863f38469c8cdd496df5525055bcce622938cb/toxcore/Messenger.c#L2442)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this should either be removed, or assigned to @mannol
> 
> The argument for removing: toxav doesn't need additional or less time, even if we do need to reduce this number for toxav (unlikely IMO) then it should be renamed to messenger min and we should ignore it when toxav is active.
> 
> finally; this should be dropped completely. Messenger isn't smarter than crypto_run_interval. and if it is, we should fix that, no this.
</details>
Assigned to mannol. I'm not changing code behaviour in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/133)*

**Pull request closed without merging**
