### PR TITLE
Added UB comment r/t deleting a friend w/ active call

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/148)

### CODE REVIEW

**Comment by GrayHatter** [comment]
closes #147

**Comment by JFreegman** [comment]
*[toxcore/Messenger.c, line 417 at r1](https://reviewable.io:443/reviews/toktok/toxcore/148#-KS-86ieb3nwxfUJe1pe:-KS-86ieb3nwxfUJe1pf:b8yjjio) ([raw file](https://github.com/toktok/toxcore/blob/e0a7d0a7d8618f3233503d70ef9310d58642012b/toxcore/Messenger.c#L417)):*
> ```C
>     if (m->friend_connectionstatuschange_internal) {
>         // This is a direct callback to tell ToxAV that the friend has disconnected.
>         // The userdata in this callback is set to NULL. Which if there is an active
> ```

Weird fragmented sentence. Should say something like: "The userdata in this callback is set to NULL,  which will get passed back to the user if there is an active call. This behavior is expected..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/148)*

**Comment by JFreegman** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/148#-:-KS-Aa0LOSWSpZ5GDp4L:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[toxcore/Messenger.c, line 417 at r1](https://reviewable.io:443/reviews/toktok/toxcore/148#-KS-86ieb3nwxfUJe1pe:-KS-AxyugJ-SmjO3quIb:b-896fix) ([raw file](https://github.com/toktok/toxcore/blob/e0a7d0a7d8618f3233503d70ef9310d58642012b/toxcore/Messenger.c#L417)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary>
> Weird fragmented sentence. Should say something like: "The userdata in this callback is set to NULL,  which will get passed back to the user if there is an active call. This behavior is expected..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/toxcore/148)*

**Pull request merged**
