### PR TITLE
[WIP] Multi device (Preview PR)

### PR DESCRIPTION
**Pull request by GrayHatter**
This PR is very unlikely to be merged, it exists for comments and overview of the progress.

The actual PR will be split into many smaller PRs that can be review easily.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxcore/7)

### CODE REVIEW

**Comment by nurupo** [comment]
>[The number of lines changed in a PR should not exceed 300. If it is a larger change, it should be broken into separate PRs. It won’t be possible to guarantee that every PR adds direct value, but in general, they should.](https://docs.google.com/document/d/1lMVNwGhyioBnMESp5JAEDbtssyPzd-SwGJJknduQZrk)

**Comment by GrayHatter** [comment]
@nurupo 

>This PR is very unlikely to be merged, it exists for comments and overview of the progress.

>The actual PR will be split into many smaller PRs that can be review easily.

**Comment by Renha** [comment]
why closed? discussion isn't needed anymore?

**Comment by GrayHatter** [comment]
@Renha just cleaning up a bit, It's not going to get merged in it's current state anyways, so there's no reason to keep *this* pull open. I'll open a new one once we get closer to actually merging mdev

**Comment by mannol** [comment]
@GrayHatter What's the state of this anyways?

**Comment by GrayHatter** [comment]
@mannol blocked by net_crypto. I need to be able to answer to >1 keypairs to give multi-device a bit more security. Then it's going to need to be refactored to all the new changes in toxcore. But it works in uTox.

**Pull request closed without merging**
