### PR TITLE
Version Tick v0.0.0 => v0.0.1

### PR DESCRIPTION
**Pull request by GrayHatter**
With the API change (making the callbacks stateless), TokTok/toxcore has
diverged enough from irungentoo/toxcore that at the very least the minor version
number needs to be incremented. Remaining on v0.0.0 is harmful to both
clients/client developers, and package maintainers.

---
This change is NOT reviewable. Use Github reviews instead.

### CODE REVIEW

**Comment by nurupo** [comment]
So, you want us to release toxcore 0.1.0 now, while being halfway done with #40? Sounds like a bad idea.

**Comment by GrayHatter** [comment]
```
<grayhatter> I want to be able to say v0.0 vs v0.1
<grayhatter> (reason for that pull)
<iphy> let's do that when stateless is done
<grayhatter> tux3 nurupo iphy
<grayhatter> do you want me to close it, or leave it open and rebase when stateless is done?
<tux3> I'd leave it open, just because I've been promised toxcore versionning for so long, and as far as I'm concerned the sooner the better!
<iphy> leave it open
```

**Comment by nurupo** [comment]
Missed that

**Comment by felix-salfelder** [comment]
the library version is set in configure.ac. what are you trying to achieve with the preprocessor defines? the linker/loader will not see them.

(yes the interface version should have been incremented some time ago, also the package version...)

**Comment by GrayHatter** [comment]
@felix-salfelder I dont care about linker/loaders, the macro changed above are convenience macros for compiling with clients. Also, see my previous comment as to the reason I want this change. It's purely for speaking convenience.

**Comment by felix-salfelder** [comment]
GrayHatter wrote
> I dont care about linker/loaders

that's fine, you don't need to. linkers and loaders aside, the version is (and hopefully will remain) written down in configure.ac, which you missed to update in this PR. imo convenience macros should be synchronized with actual versions, that's why i was wondering.

nurupo wrote

> So, you want us to release toxcore 0.1.0 now, while being halfway done with #40? Sounds like a bad idea

that makes sense. let me suggest to release 0.0.0 before 0.1.0... (regardless of #40). but: are there any release plans at all? and which project or developer would be in charge then?

thanks

**Comment by GrayHatter** [comment]
@felix-salfelder there's no such thing as version v0.0.0 in toxcore. If you have your heart set on getting a v0.0.0 release, you'd have to ask @irungentoo and I assume he'll point you to https://github.com/irungentoo/toxcore/archive/master.tar.gz

**Comment by felix-salfelder** [comment]
> If you have your heart set on getting a v0.0.0 release

i have not invented the way software is being packaged and distributed. this thread, indicates that releases will also help your own client development, go figure.

> you'd have to ask @irungentoo 

i did, see https://github.com/irungentoo/toxcore/issues/1610. there you replied "[..] not likely [t]here", but without explanation. you seem to be more active, but are you a tox (as in toxcore, tox "the library") developer at all?

**Comment by iphydf** [comment]
Can you rebase this, and look around to make sure you caught all the places (cmake, configure, code) where 0.0.0 needs to be updated to 0.1.0?

**Comment by GrayHatter** [comment]
@iphydf done

**Comment by GrayHatter** [comment]
Changed from `v0.1.0` to `v0.0.1`

**Comment by iphydf** [comment]
Can you remove all the scripts and just change the versions? Perhaps for the LT_VERSION you can use the version components (if autoconf provides those) so we have one less place to update.

**Pull request closed without merging**
